#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""D2 게이트 4 수정 반영: MSG 대조에서 발견된 이름/숫자/인용구 누락·오류 수정.
   파일은 \\uXXXX 이스케이프를 사용하므로 replacement에도 동일 형식을 쓴다."""
import io

FIXES = [
 # batch1
 ('work_d2/batch1_13_16.py',
  "A priest of a god that doesn't even exist!",
  "A priest of No-God!"),
 ('work_d2/batch1_13_16.py',
  "존재하지도 않는 신의 제사장이라고!",
  "No-God의 제사장이라고!"),
 # batch3
 ('work_d2/batch3_21_25.py',
  "Zechariah, Azariah, Michael, and Shephatiah",
  "Zechariah, Azariahu, Michael, and Shephatiah"),
 ('work_d2/batch3_21_25.py',
  "스가랴, 아사랴, 미가엘, 스바댜",
  "스가랴, 아사랴후, 미가엘, 스바댜"),
 ('work_d2/batch3_21_25.py',
  "The only one left was Jehoahaz, his youngest son.",
  "The only one left was Ahaziah, his youngest son."),
 ('work_d2/batch3_21_25.py',
  "남은 건 막내 아들 여호아하스뿐이었지.",
  "남은 건 막내 아들 아하시야뿐이었지."),
 ('work_d2/batch3_21_25.py',
  "recover from the wounds he got in the battle at Ramoth Gilead against Hazael, king of Aram",
  "recover from the wounds he got in Ramah in the war against Hazael, king of Aram"),
 ('work_d2/batch3_21_25.py',
  "길르앗 라못 전투에서 아람 왕 하사엘에게 입은 상처를 치료하려고",
  "라맛에서 아람 왕 하사엘과의 전쟁에서 입은 상처를 치료하려고"),
 ('work_d2/batch3_21_25.py',
  "gave him the copies of the laws, and made him king",
  "handed him the scroll of God's covenant, and made him king"),
 ('work_d2/batch3_21_25.py',
  "율법 사본을 주고, 왕으로 세웠어",
  "하나님의 언약 두루마리를 주고, 왕으로 세웠어"),
 ('work_d2/batch3_21_25.py',
  "to offer Whole-Burnt-Offerings to God according to the law of Moses, and to praise in song",
  "to offer Whole-Burnt-Offerings to God as set out in The Revelation of Moses, and to praise in song"),
 ('work_d2/batch3_21_25.py',
  "모세의 율법대로 하나님께 번제를 드리고 노래로 찬양하도록",
  "모세의 계시에 기록된 대로 하나님께 번제를 드리고 노래로 찬양하도록"),
 ('work_d2/batch3_21_25.py',
  "His mother was Zibiah, from Beersheba.",
  "His mother was Gazelle (Zibiah), from Beersheba."),
 ('work_d2/batch3_21_25.py',
  "어머니는 브엘세바 출신 시브야였지",
  "어머니는 브엘세바 출신 가젤(시브야)였지"),
 ('work_d2/batch3_21_25.py',
  "(Athaliah's sons had broken into The Temple of God",
  "(wicked Queen Athaliah and her sons had broken into The Temple of God"),
 ('work_d2/batch3_21_25.py',
  "(아달랴의 아들들이 하나님의 성전을 침입해",
  "(사악한 아달랴 여왕과 그 아들들이 하나님의 성전을 침입해"),
 ('work_d2/batch3_21_25.py',
  "His mother was Jehoaddan from Jerusalem.",
  "His mother was Jehoaddin from Jerusalem."),
 ('work_d2/batch3_21_25.py',
  "어머니는 예루살렘 출신 여호앗단이였지",
  "어머니는 예루살렘 출신 여호앗딘이였지"),
 ('work_d2/batch3_21_25.py',
  "Amaziah organized Judah and sorted out the army by families",
  "Amaziah organized Judah and sorted out Judah and Benjamin by families"),
 ('work_d2/batch3_21_25.py',
  "아마샤가 유다를 조직하고 군대를 가문별로",
  "아마샤가 유다를 조직하고 유다와 베냐민을 가문별로"),
 ('work_d2/batch3_21_25.py',
  "because God is not on their side and will make you fall flat on your face",
  "because God is not on their side \\u2014 not with any of the Ephraimites \\u2014 and will make you fall flat on your face"),
 ('work_d2/batch3_21_25.py',
  "하나님이 그들 편이 아니시라 얼굴을 땅에 박게 하실 겁니다",
  "하나님이 그들 편이 아니시고 \\u2014 에브라임 사람 그 누구와도 함께하지 않으시니 \\u2014 얼굴을 땅에 박게 하실 겁니다"),
 ('work_d2/batch3_21_25.py',
  "marched them to the top of the cliff and threw them down",
  "marched them to the top of the Rock and threw them down"),
 ('work_d2/batch3_21_25.py',
  "절벽 꼭대기로 끌고 가서 던져버렸어",
  "셀라 바위 꼭대기로 끌고 가서 던져버렸어"),
 # batch4
 ('work_d2/batch4_26_29.py',
  "Under them were 307,500 trained soldiers ready for battle to help the king fight against enemies.",
  "Under them were 307,000 trained soldiers ready for battle to help the king fight against enemies, with 500 of them on constant alert."),
 ('work_d2/batch4_26_29.py',
  "그 아래 원수를 치는 데 왕을 도울 훈련된 병사 307,500명.",
  "그 아래 원수를 치는 데 왕을 도울 훈련된 병사 307,000명. 그중 500명은 항상 경계 근무 중이었지."),
 ('work_d2/batch4_26_29.py',
  "61,000 bushels of wheat, and 61,000 bushels of barley",
  "65,000 bushels of wheat, and 65,000 bushels of barley"),
 ('work_d2/batch4_26_29.py',
  "밀 61,000부셀, 보리 61,000부셀",
  "밀 65,000부셀, 보리 65,000부셀"),
 ('work_d2/batch4_26_29.py',
  "He burned incense in the Valley of Hinnom",
  "He burned incense in the Valley of Ben Hinnom"),
 ('work_d2/batch4_26_29.py',
  "힌놈 골짜기에서 분향하며",
  "벤힌놈 골짜기에서 분향하며"),
 ('work_d2/batch4_26_29.py',
  "who killed a lot of people in a single day \\u2014 120,000 stalwart soldiers \\u2014 because",
  "who killed 120,000 in a single day \\u2014 all first-class soldiers \\u2014 because"),
 ('work_d2/batch4_26_29.py',
  "하루에 엄청난 사람을 죽였어. 건장한 병사 12만 명. 조상들의 하나님을 버렸기 때문이야.",
  "하루에 12만 명을 죽였어. 모두 일류 병사들이었지. 조상들의 하나님을 버렸기 때문이야."),
 ('work_d2/batch4_26_29.py',
  "Shimri and Jeuel (from the Elizaphanites)",
  "Shimri and Jeiel (from the Elizaphanites)"),
 ('work_d2/batch4_26_29.py',
  "시므리와 여우엘(엘리사반 자손)",
  "시므리와 여이엘(엘리사반 자손)"),
 # batch5
 ('work_d2/batch5_30_33.py',
  "was in charge of the freewill offerings to God",
  "was in charge of the Freewill-Offerings of God"),
 ('work_d2/batch5_30_33.py',
  "He fortified the defensive complex of the City of David.",
  "He reinforced the defensive rampart (the Millo) of the old City of David."),
 ('work_d2/batch5_30_33.py',
  "다윗 성의 방어 시설을 견고히 했지.",
  "옛 다윗 성의 방어 성벽(밀로)을 보강했지."),
 ('work_d2/batch5_30_33.py',
  "as sacrifices in the Valley of Hinnom",
  "as sacrifices in the Valley of Ben Hinnom"),
 ('work_d2/batch5_30_33.py',
  "힌놈 골짜기에서 아들들을 불에 제물로 태웠어",
  "벤힌놈 골짜기에서 아들들을 불에 제물로 태웠어"),
 ('work_d2/batch5_30_33.py',
  "is written down in The History of the Kings of Israel.",
  "is written down in The Chronicles of the Kings of Israel."),
 ('work_d2/batch5_30_33.py',
  "is written down in The History of the Seers.",
  "is described in the records of the prophets."),
 ('work_d2/batch5_30_33.py',
  "이스라엘 열왕 역사에 기록되어 있어",
  "이스라엘 왕들의 연대기에 기록되어 있어"),
 ('work_d2/batch5_30_33.py',
  "선견자들의 역사에 기록되어 있지",
  "선지자들의 기록에 묘사되어 있지"),
 # batch6
 ('work_d2/batch6_34_36.py',
  "Zechariah and Meshullam, the Kohathite Levites",
  "Zechariah and Meshullam from the Kohathites"),
 ('work_d2/batch6_34_36.py',
  "그핫 레위인 스가랴와 므술람이었지",
  "그핫 사람들 출신 스가랴와 므술람이었지"),
]

import os
os.chdir('/home/hatch/workspace/teenz-bible-review')
failed = []
for path, old, new in FIXES:
    s = io.open(path, encoding='utf-8').read()
    if old not in s:
        failed.append((path, old[:60])); continue
    s = s.replace(old, new, 1)
    io.open(path, 'w', encoding='utf-8').write(s)
if failed:
    print('FAILED:')
    for p, o in failed: print(' ', p, '::', o)
else:
    print(f'OK: {len(FIXES)} replacements applied')
