# -*- coding: utf-8 -*-
"""2Chronicles teen EN/KO chapters 1-12 (작업자 D3, 2026-09-24).
D2 스키마와 동일: CHAPTERS[ch] = {'title_en','title_ko','units':[{'badge','mr','header_en','header_ko','en','ko'}], 'splits':[], 'changes':[]}.
MSG 문단 배지 1:1. 작성과 동시에 MSG 전수 대조(게이트 1) 반영.
"""
CHAPTERS = {
1: {'title_en': "Solomon's Wise Request", 'title_ko': '솔로몬의 지혜로운 요청', 'units': [
{'badge': '1-6', 'mr': '1-6', 'header_en': 'King Solomon', 'header_ko': '솔로몬 왕',
 'en': "Solomon, David's son, took a firm grip on the reins of his kingdom. God was with him and gave him a ton of help. Solomon called together all of Israel — the commanders and captains, the judges, every leader, and all the heads of families. Then Solomon and the whole company went to the worship center at Gibeon. That's where the Tent of Meeting of God was — the one Moses, the servant of God, had made in the wilderness. The Chest of God, though, was in Jerusalem — David had brought it up from Kiriath Jearim, set up a special place for it, and pitched a tent for it. But the Bronze Altar that Bezalel, son of Uri, the son of Hur, had made was in Gibeon, right where it belonged in front of the Tabernacle of God. That's where Solomon and the congregation gathered to pray. Solomon worshiped God at the Bronze Altar in front of the Tent of Meeting, and sacrificed a thousand Whole-Burnt-Offerings on it.",
 'ko': '다윗의 아들 솔로몬이 왕국의 고삐를 단단히 잡았어. 하나님이 그와 함께하셔서 큰 도움을 주셨지. 솔로몬이 온 이스라엘을 불러 모았어. 지휘관들과 대장들, 재판관들, 모든 지도자, 그리고 각 가문의 우두머리들까지. 그리고 솔로몬과 온 무리가 기브온의 예배 처소로 갔어. 거기에 하나님의 회막이 있었거든. 하나님의 종 모세가 광야에서 만든 바로 그 회막이야. 하나님의 궤는 예루살렘에 있었지. 다윗이 기럇여아림에서 메고 올라와서 특별한 자리를 마련하고 장막을 쳐 둔 거야. 하지만 우리 아들 후르의 아들인 브살렐이 만든 놋제단은 기브온에 있었어. 하나님의 성막 앞 원래 자리에. 솔로몬과 회중이 기도하러 모인 곳이 바로 거기였지. 솔로몬이 회막 앞 놋제단에서 하나님께 예배하고, 그 위에 번제 천 마리를 드렸어.'},
{'badge': '7', 'mr': '7',
 'en': 'That night God appeared to Solomon. God said, "What do you want from me? Ask."',
 'ko': '그날 밤 하나님이 솔로몬에게 나타나셨어. 하나님이 말씀하셨어. “내게 무엇을 원하느냐? 구해봐.”'},
{'badge': '8-10', 'mr': '8-10',
 'en': 'Solomon answered, "You were extravagantly generous with my father David, and now you have made me king in his place. Establish, God, the words you spoke to my father — because you\'ve given me a staggering task, ruling this mob of people. Yes, give me wisdom and knowledge as I come and go among this people — for who on his own is capable of leading these, your glorious people?"',
 'ko': '솔로몬이 대답했어. “아버지 다윗에게 정말 후하게 베풀어주셨는데, 이제 저를 그 자리에 왕으로 세우셨습니다. 하나님, 아버지께 하신 말씀을 이루어주세요. 저에게 엄청난 과제를 맡기셨잖아요. 이 많은 백성을 다스리는 일 말이에요. 이 백성 가운데 오가며 지혜와 지식을 주소서. 혼자 힘으로 이 영광스러운 주의 백성을 이끌 수 있는 사람이 누가 있겠습니까?”'},
{'badge': '11-12', 'mr': '11-12',
 'en': 'God answered Solomon, "This is what has come out of your heart: You didn\'t grasp for money, wealth, fame, and the doom of your enemies; you didn\'t even ask for a long life. You asked for wisdom and knowledge so you could govern well my people over whom I\'ve made you king. Because of this, you get what you asked for — wisdom and knowledge. And I\'m presenting you the rest as a bonus — money, wealth, and fame beyond anything the kings before or after you had or will have."',
 'ko': '하나님이 솔로몬에게 대답하셨어. “네 마음에서 나온 게 바로 이것이다. 돈도, 부도, 명성도, 원수들의 멸망도 움켜쥐려 하지 않았고, 장수조차 구하지 않았구나. 네가 다스리게 한 내 백성을 잘 다스리려고 지혜와 지식을 구했구나. 그러니 구한 것을 주겠다. 지혜와 지식 말이다. 그리고 나머지는 덤으로 주겠다. 너 앞뒤의 어떤 왕도 갖지 못했고 갖지 못할 돈과 부와 명성을.”'},
{'badge': '13', 'mr': '13',
 'en': "Then Solomon left the worship center at Gibeon and the Tent of Meeting and went to Jerusalem. He set to work as king of Israel.",
 'ko': '그러고 나서 솔로몬이 기브온의 예배 처소와 회막을 떠나 예루살렘으로 갔어. 이스라엘의 왕으로서 일을 시작했지.'},
{'badge': '14-17', 'mr': '14-17',
 'en': "Solomon collected chariots and horses: fourteen hundred chariots and twelve thousand horses! He stabled them in the special chariot-cities as well as in Jerusalem. The king made silver and gold as common as rocks, and cedar as common as the fig trees in the lowland hills. His horses were brought in from Egypt and Cilicia, specially acquired by the king's agents. Chariots from Egypt went for fifteen pounds of silver and a horse for about three and three-quarters of a pound of silver. Solomon carried on a brisk horse-trading business with the Hittite and Aramean royal houses.",
 'ko': '솔로몬이 전차와 말을 모았어. 전차 1,400대, 말 12,000필! 전차 전용 성읍들과 예루살렘에 두었지. 왕은 은과 금을 돌처럼 흔하게, 백향목을 저지대 언덕의 무화과나무처럼 흔하게 만들었어. 말들은 애굽과 길리기아에서 들여왔는데, 왕의 대리인들이 특별히 사들인 거야. 애굽산 전차는 은 15파운드, 말은 은 3.75파운드 정도였어. 솔로몬은 헷과 아람 왕가들과 활발한 말 무역을 했어.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 1장 6문단 1:1 매핑; MSG 대조 완료)']},
2: {'title_en': 'Planning the Temple', 'title_ko': '성전 건축 계획', 'units': [
{'badge': '1', 'mr': '1', 'header_en': 'The Temple Construction Begins', 'header_ko': '성전 건축 시작',
 'en': "Solomon gave orders to begin construction on the house of worship in honor of God and a palace for himself.",
 'ko': '솔로몬이 하나님을 기리는 예배의 집과 자기 궁전을 짓기 시작하라는 명령을 내렸어.'},
{'badge': '2', 'mr': '2',
 'en': "Solomon assigned seventy thousand common laborers, eighty thousand to work the quarries in the mountains, and thirty-six hundred foremen to manage the workforce.",
 'ko': '솔로몬이 일반 노동자 7만 명, 산의 채석장에서 일할 인부 8만 명, 그리고 인력을 관리할 감독 3,600명을 배치했어.'},
{'badge': '3-4', 'mr': '3-4',
 'en': 'Then Solomon sent this message to King Hiram of Tyre: "Send me cedar logs, the same kind you sent my father David for building his palace. I\'m about to build a house of worship in honor of God, a holy place for burning perfumed incense, for setting out holy bread, for making Whole-Burnt-Offerings at morning and evening worship, and for Sabbath, New Moon, and Holy Day services of worship — the acts of worship required of Israel.',
 'ko': '그러고 나서 솔로몬이 두로 왕 히람에게 이런 전갈을 보냈어. “아버지 다윗의 궁전을 지을 때 보내주셨던 그 백향목 재목을 보내주세요. 저는 하나님을 기리는 예배의 집을 지으려고 합니다. 향기로운 향을 피우고, 거룩한 떡을 차려놓고, 아침저녁 예배에 번제를 드리고, 안식일과 초하루와 성일에 예배드리는 거룩한 곳이죠. 이스라엘이 마땅히 드려야 할 예배 행위들입니다.'},
{'badge': '5-10', 'mr': '5-10',
 'en': '"The house I am building has to be the best, for our God is the best, far better than competing gods. But who is capable of building such a structure? Why, the skies — the entire cosmos! — can\'t begin to contain him. And me, who am I to think I can build a house adequate for God — burning incense to him is about all I\'m good for! I need your help: Send me a master artisan in gold, silver, bronze, iron, textiles of purple, crimson, and violet, and who knows the craft of engraving; he will supervise the trained craftsmen in Judah and Jerusalem that my father provided. Also send cedar, cypress, and algum logs from Lebanon; I know you have lumberjacks experienced in the Lebanon forests. I\'ll send workers to join your crews to cut plenty of timber — I\'m going to need a lot, for this house I\'m building is going to be absolutely stunning — a showcase temple! I\'ll provide all the food necessary for your crew of lumberjacks and loggers: 130,000 bushels of wheat, 120,000 gallons of wine, and 120,000 gallons of olive oil."',
 'ko': '“제가 짓는 집은 최고여야 합니다. 우리 하나님이 최고시니까요. 다른 신들보다 훨씬 뛰어나시죠. 그런데 누가 그런 건물을 지을 수 있겠습니까? 하늘, 온 우주조차 그분을 담기 시작도 못 하는데요. 제가 누군데 하나님께 합당한 집을 짓겠다고 생각하겠습니까. 그분께 향 피우는 정도가 제가 할 수 있는 전부죠! 도움이 필요합니다. 금·은·놋·쇠를 다루고 자주·홍·청색 직물을 짜며 조각 기술을 아는 명장을 보내주세요. 아버지가 남겨주신 유다와 예루살렘의 숙련공들을 감독할 사람입니다. 또 레바논에서 백향목, 잣나무, 백단목 재목을 보내주세요. 레바논 삼림에 익숙한 벌목꾼들이 있는 걸 압니다. 제 일꾼들을 보내서 함께 목재를 많이 베게 하겠습니다. 많이 필요할 거예요. 제가 짓는 이 집은 정말 눈부실 겁니다. 자랑할 만한 성전이죠! 벌목 일꾼들에게 필요한 식량은 제가 다 댈게요. 밀 13만 부셸, 포도주 12만 갤런, 올리브유 12만 갤런입니다.”'},
{'badge': '11', 'mr': '11',
 'en': 'Hiram king of Tyre wrote Solomon in reply: "It\'s plain that God loves his people — he made you king over them!"',
 'ko': '두로 왕 히람이 솔로몬에게 답장을 썼어. “하나님이 자기 백성을 사랑하시는 게 분명하오. 당신을 그들의 왕으로 세우셨으니!”'},
{'badge': '12-14', 'mr': '12-14',
 'en': 'He wrote on, "Blessed be the God of Israel, who made heaven and earth, and who gave King David a son so wise, so knowledgeable and shrewd, to build a temple for God and a palace for himself. I\'ve sent you Huram-Abi — he\'s already on his way — he knows the construction business inside and out. His mother is from Dan and his father from Tyre. He knows how to work in gold, silver, bronze, iron, stone, and wood, in purple, violet, linen, and crimson textiles; he is also an expert engraver and competent to work out designs with your artists and architects, and those of my master David, your father.',
 'ko': '이어서 이렇게 썼어. “천지를 만드시고 다윗 왕에게 이토록 지혜롭고 박식하고 슬기로운 아들을 주셔서 하나님을 위한 성전과 자기 궁전을 짓게 하신 이스라엘의 하나님을 찬양합니다. 후람아비를 보냈소. 이미 출발했소. 건축 일을 속속들이 아는 사람이오. 어머니는 단 지파 출신이고 아버지는 두로 사람이오. 금·은·놋·쇠·돌·나무를 다루고, 자주·청색·모시·홍색 직물을 짜는 법을 알지요. 조각의 대가이기도 해서 당신의 예술가·건축가들, 그리고 내 주인이신 당신의 아버지 다윗의 사람들과 함께 설계를 짜낼 수 있을 거요.'},
{'badge': '15-16', 'mr': '15-16',
 'en': '"Go ahead and send the wheat, barley, olive oil, and wine you promised for my work crews. We\'ll log the trees you need from the Lebanon forests and raft them down to Joppa. You\'ll have to get the timber up to Jerusalem yourself."',
 'ko': '“약속하신 밀, 보리, 올리브유, 포도주를 제 일꾼들에게 보내주시오. 레바논 삼림에서 필요한 나무를 베어 뗏목으로 욥바까지 내려보내겠소. 목재를 예루살렘까지 올리는 건 직접 하셔야 하오.”'},
{'badge': '17-18', 'mr': '17-18',
 'en': "Solomon then took a census of all the foreigners living in Israel, using the same census-taking method employed by his father. They numbered 153,600. He assigned 70,000 of them as common laborers, 80,000 to work the quarries in the mountains, and 3,600 as foremen to manage the work crews.",
 'ko': '솔로몬이 그다음에 이스라엘에 사는 모든 외국인을 인구조사했어. 아버지가 쓰던 방식 그대로. 모두 153,600명이었지. 그중 7만 명을 일반 노동자로, 8만 명을 산의 채석장 인부로, 3,600명을 작업반을 관리할 감독으로 배치했어.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 2장 8문단 1:1 매핑; MSG 대조 완료)']},
3: {'title_en': 'Building the Temple', 'title_ko': '성전 짓기', 'units': [
{'badge': '1-4', 'mr': '1-4', 'header_en': 'The Temple', 'header_ko': '성전',
 'en': "So Solomon broke ground, launched construction of the house of God in Jerusalem on Mount Moriah, the place where God had appeared to his father David. The precise site, the threshing floor of Araunah the Jebusite, had been designated by David. He broke ground on the second day in the second month of the fourth year of his rule. These are the dimensions that Solomon set for the construction of the house of God: ninety feet long and thirty feet wide. The porch in front stretched the width of the building, that is, thirty feet; and it was thirty feet high.",
 'ko': '그래서 솔로몬이 착공했어. 예루살렘 모리아 산, 하나님이 아버지 다윗에게 나타나셨던 그곳에 하나님의 집 짓기를 시작한 거야. 정확한 부지는 여부스 사람 아라우나의 타작마당으로, 다윗이 지정해둔 곳이었지. 다스린 지 4년째 되던 해 2월 2일에 첫 삽을 떴어. 솔로몬이 정한 하나님의 집 치수는 이랬어. 길이 90피트, 너비 30피트. 앞 현관은 건물 너비만큼 쭉 뻗었어. 그러니까 30피트, 높이는 30피트였지.'},
{'badge': '4-7', 'mr': '4-7',
 'en': "The interior was gold-plated. He paneled the main hall with cypress and veneered it with fine gold engraved with palm tree and chain designs. He decorated the building with precious stones and gold from Parvaim. Everything was coated with gold veneer: rafters, doorframes, walls, and doors. Cherubim were engraved on the walls.",
 'ko': '내부는 금으로 도금했어. 본당을 잣나무로 널판하고, 종려나무와 사슬 무늬를 새긴 순금으로 입혔지. 보석과 바르와임 산 금으로 건물을 장식했어. 서까래, 문틀, 벽, 문까지 모든 게 금판으로 덮였어. 벽에는 그룹들이 새겨져 있었지.'},
{'badge': '8-9', 'mr': '8-9',
 'en': "He made the Holy of Holies a cube, thirty feet wide, long, and high. It was veneered with six hundred talents (something over twenty-two tons) of gold. The gold nails weighed fifty shekels (a little over a pound). The upper rooms were also veneered in gold.",
 'ko': '지성소는 한 변이 30피트인 정육면체로 만들었어. 금 600달란트(약 22톤이 넘어)를 입혔지. 금 못은 50세겔(약 1파운드가 조금 넘어) 나갔어. 위층 방들도 금으로 입혔어.'},
{'badge': '10-13', 'mr': '10-13',
 'en': "He made two sculptures of cherubim, gigantic angel-like figures, for the Holy of Holies, both veneered with gold. The combined wingspread of the side-by-side cherubim (each wing measuring seven and a half feet) stretched from wall to wall, thirty feet. They stood erect facing the main hall.",
 'ko': '지성소에 그룹 조각 두 개를 만들었어. 천사 같은 거대한 형상으로, 둘 다 금을 입혔지. 나란히 선 그룹들의 날개를 합친 너비(날개 하나가 7.5피트)가 벽에서 벽까지 30피트에 닿았어. 본당을 향해 똑바로 서 있었지.'},
{'badge': '14', 'mr': '14',
 'en': "He fashioned the curtain of violet, purple, and crimson fabric and worked a cherub design into it.",
 'ko': '청색, 자주색, 홍색 천으로 휘장을 만들고 그 안에 그룹 무늬를 수놓았어.'},
{'badge': '15-17', 'mr': '15-17',
 'en': "He made two huge free-standing pillars, each fifty-two feet tall, their capitals extending another seven and a half feet. The top of each pillar was set off with an elaborate filigree of chains, like necklaces, from which hung a hundred pomegranates. He placed the pillars in front of The Temple, one on the right, and the other on the left. The right pillar he named Jakin (Security) and the left pillar he named Boaz (Stability).",
 'ko': '자립형 대왕 기둥 두 개를 만들었어. 각각 52피트 높이였고, 기둥머리가 7.5피트 더 올라갔지. 각 기둥 꼭대기는 목걸이 같은 정교한 사슬 세공으로 장식했는데, 거기에 석류 100개가 달려 있었어. 기둥들을 성전 앞에 세웠는데, 하나는 오른쪽에, 다른 하나는 왼쪽에. 오른쪽 기둥은 야긴(확고함), 왼쪽 기둥은 보아스(견고함)라고 이름 지었어.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 3장 6문단 1:1 매핑; MSG 대조 완료)']},
4: {'title_en': 'Temple Furnishings', 'title_ko': '성전 기물들', 'units': [
{'badge': '1', 'mr': '1', 'header_en': 'Temple Furnishings', 'header_ko': '성전 기물',
 'en': "He made the Bronze Altar thirty feet long, thirty feet wide, and ten feet high.",
 'ko': '놋제단을 만들었어. 길이 30피트, 너비 30피트, 높이 10피트였지.'},
{'badge': '2-5', 'mr': '2-5',
 'en': "He made a Sea — an immense round basin of cast metal fifteen feet in diameter, seven and a half feet high, and forty-five feet in circumference. Just under the rim, there were two parallel bands of something like bulls, ten to each foot and a half. The figures were cast in one piece with the Sea. The Sea was set on twelve bulls, three facing north, three facing west, three facing south, and three facing east. All the bulls faced outward and supported the Sea on their hindquarters. The Sea was three inches thick and flared at the rim like a cup, or a lily. It held about 18,000 gallons.",
 'ko': '바다를 만들었어. 주조한 금속으로 만든 거대한 둥근 대야인데, 지름 15피트, 높이 7.5피트, 둘레 45피트였지. 가장자리 바로 아래에는 황소 같은 형상이 두 줄로 나란히 있었어. 1.5피트마다 열 개씩. 그 형상들은 바다와 한 덩어리로 주조됐지. 바다는 열두 마리 황소 위에 놓였어. 셋은 북쪽, 셋은 서쪽, 셋은 남쪽, 셋은 동쪽을 향했지. 황소들은 모두 바깥을 향하고 엉덩이로 바다를 받치고 있었어. 바다의 두께는 3인치였고 가장자리는 잔이나 백합처럼 벌어졌지. 약 18,000갤런이 들어갔어.'},
{'badge': '6', 'mr': '6',
 'en': "He made ten Washbasins, five set on the right and five on the left, for rinsing the things used for the Whole-Burnt-Offerings. The priests washed themselves in the Sea.",
 'ko': '물두멍 열 개를 만들었어. 오른쪽에 다섯 개, 왼쪽에 다섯 개를 두고 번제에 쓰는 기구들을 헹구는 용도였지. 제사장들은 바다에서 몸을 씻었어.'},
{'badge': '7', 'mr': '7',
 'en': "He made ten gold Lampstands, following the specified pattern, and placed five on the right and five on the left.",
 'ko': '정해진 양식대로 금 등잔대 열 개를 만들어서 오른쪽에 다섯 개, 왼쪽에 다섯 개를 놓았어.'},
{'badge': '8', 'mr': '8',
 'en': "He made ten tables and set five on the right and five on the left. He also made a hundred gold bowls.",
 'ko': '상 열 개를 만들어 오른쪽에 다섯 개, 왼쪽에 다섯 개를 두었어. 금 대접도 백 개 만들었지.'},
{'badge': '9', 'mr': '9',
 'en': "He built a Courtyard especially for the priests and then the great court and doors for the court. The doors were covered with bronze.",
 'ko': '제사장들을 위한 뜰을 따로 짓고, 그다음 큰 뜰과 뜰 문들을 만들었어. 문들은 놋으로 입혔지.'},
{'badge': '10', 'mr': '10',
 'en': "He placed the Sea on the right side of The Temple at the southeast corner.",
 'ko': '바다는 성전 오른쪽 남동쪽 모서리에 두었어.'},
{'badge': '11-16', 'mr': '11-16',
 'en': "He also made ash buckets, shovels, and bowls. And that about wrapped it up: Huram completed the work he had contracted to do for King Solomon — two pillars; two bowl-shaped capitals for the tops of the pillars; two decorative filigrees for the capitals; four hundred pomegranates for the filigrees (a double row of pomegranates for each filigree); ten washstands with their basins; one Sea and the twelve bulls under it; miscellaneous buckets, forks, shovels, and bowls.",
 'ko': '재받이, 부삽, 대접도 만들었어. 그리고 후람이 솔로몬 왕과 계약한 일을 대충 다 마쳤어. 기둥 두 개, 기둥 꼭대기용 대접 모양 기둥머리 두 개, 기둥머리용 장식 세공 두 개, 세공용 석류 400개(세공마다 석류 두 줄씩), 물두멍 받침 열 개와 그 대야들, 바다 하나와 그 아래 황소 열두 마리, 그리고 자질구레한 재받이, 고기 갈고리, 부삽, 대접들.'},
{'badge': '16-18', 'mr': '16-18',
 'en': "All these artifacts that Huram-Abi made for King Solomon for The Temple of God were made of burnished bronze. The king had them cast in clay in a foundry on the Jordan plain between Succoth and Zarethan. These artifacts were never weighed — there were far too many! Nobody has any idea how much bronze was used.",
 'ko': '후람아비가 솔로몬 왕을 위해 하나님의 성전에 만든 이 기물들은 모두 닦은 놋으로 만들었어. 왕이 숙곳과 사르단 사이 요단 평야의 주조장에서 진흙 거푸집에 부어 만들게 했지. 이 기물들은 무게를 달아보지도 않았어. 너무 많았거든! 놋이 얼마나 쓰였는지 아는 사람이 아무도 없어.'},
{'badge': '19-22', 'mr': '19-22',
 'en': "Solomon was also responsible for the furniture and accessories in The Temple of God: the gold Altar; the tables that held the Bread of the Presence; the Lampstands of pure gold with their lamps, to be lighted before the Inner Sanctuary, the Holy of Holies; the gold flowers, lamps, and tongs (all solid gold); the gold wick trimmers, bowls, ladles, and censers; the gold doors of The Temple, doors to the Holy of Holies, and the doors to the main sanctuary.",
 'ko': '솔로몬은 하나님의 성전 안 가구와 부속품도 맡았어. 금 제단, 진설병을 차리는 상들, 지성소 곧 내전 앞에 켜 둘 순금 등잔대와 그 등잔들, 금꽃과 등잔과 부집게(전부 순금), 금 심지 가위와 대접과 국자와 향로, 성전의 금 문들, 지성소 문들, 본당 문들.'},
], 'splits': [{'msg_range': '16', 'paras': [8, 9], 'note': "MSG 자체 문단 경계가 16절을 가름: [11-16]은 후람 작업 목록('ten washstands with their basins; one Sea and the twelve bulls...')에서 끝나고, [16-18]은 'All these artifacts that Huram-Abi made for King Solomon...'에서 시작. Teenz도 MSG 경계 그대로 유지. 편집적 split 아님."}], 'changes': ['초벌 작성 (MSG 4장 10문단 1:1 매핑; MSG 대조 완료)']},
5: {'title_en': 'The Chest Comes Home', 'title_ko': '언약궤가 돌아오다', 'units': [
{'badge': '1', 'mr': '1',
 'en': "That completed the work King Solomon did on The Temple of God. He then brought in the holy offerings of his father David, the silver and the gold and the artifacts. He placed them all in the treasury of God's Temple.",
 'ko': '솔로몬 왕이 하나님의 성전에 한 일이 이렇게 다 끝났어. 그리고 아버지 다윗이 바친 거룩한 예물들, 은과 금과 기물들을 들여와서 하나님의 성전 곳간에 모두 두었지.'},
{'badge': '2-3', 'mr': '2-3', 'header_en': 'Installing the Chest', 'header_ko': '언약궤 봉안',
 'en': "Bringing all this to a climax, Solomon got all the leaders together in Jerusalem — all the chiefs of tribes and the family patriarchs — to move the Chest of the Covenant of God from Zion and install it in The Temple. All the men of Israel assembled before the king on the feast day of the seventh month, the Feast of Booths.",
 'ko': '대미를 장식하려고 솔로몬이 모든 지도자를 예루살렘에 모았어. 각 지파의 우두머리들과 가문의 원로들. 하나님의 언약궤를 시온에서 메어다가 성전에 봉안하려는 거야. 일곱째 달 명절, 초막절 날에 온 이스라엘 남자들이 왕 앞에 모였지.'},
{'badge': '4-6', 'mr': '4-6',
 'en': "When all the leaders of Israel were ready, the Levites took up the Chest. They carried the Chest, the Tent of Meeting, and all the sacred things in the Tent used in worship. The priests, all Levites, carried them. King Solomon and the entire congregation of Israel were there before the Chest, worshiping and sacrificing huge numbers of sheep and cattle — so many that no one could keep track.",
 'ko': '이스라엘의 모든 지도자가 준비되자 레위인들이 궤를 메었어. 궤와 회막, 그리고 회막에서 예배에 쓰는 모든 거룩한 기구들을 메었지. 제사장들, 모두 레위인인 그들이 메었어. 솔로몬 왕과 온 이스라엘 회중이 궤 앞에서 예배하며 양과 소를 엄청나게 잡아 제사로 드렸어. 너무 많아서 셀 수가 없을 정도였지.'},
{'badge': '7-10', 'mr': '7-10',
 'en': "The priests brought the Chest of the Covenant of God to its place in the Inner Sanctuary, the Holy of Holies, under the wings of the cherubim. The outspread wings of the cherubim formed a canopy over the Chest and its poles. The ends of the poles were so long that they stuck out from the entrance of the Inner Sanctuary, but were not noticeable further out — they're still there today. There was nothing in the Chest itself but the two stone tablets that Moses had placed in it at Horeb where God made a covenant with Israel after bringing them up from Egypt.",
 'ko': '제사장들이 하나님의 언약궤를 내전, 곧 지성소의 자리로, 그룹들의 날개 아래로 가져다 놓았어. 펼친 그룹 날개가 궤와 그 채를 덮는 천개가 되었지. 채 끝이 너무 길어서 내전 입구 밖으로 삐져나왔는데, 더 바깥에서는 보이지 않았어. 지금도 거기 그대로 있어. 궤 안에는 모세가 호렙에서 넣은 돌판 두 개밖에 없었어. 하나님이 이스라엘을 애굽에서 데려오신 뒤 그들과 언약을 맺으신 곳에서 말이야.'},
{'badge': '11-13', 'mr': '11-13',
 'en': "The priests then left the Holy Place. All the priests there were consecrated, regardless of rank or assignment; and all the Levites who were musicians were there — Asaph, Heman, Jeduthun, and their families, dressed in their worship robes; the choir and orchestra assembled on the east side of the Altar and were joined by 120 priests blowing trumpets. The choir and trumpets made one voice of praise and thanks to God — orchestra and choir in perfect harmony singing and playing praise to God: Yes! God is good! His loyal love goes on forever!",
 'ko': '그러고 나서 제사장들이 성소를 나왔어. 거기 있던 제사장들은 직급이나 임무에 상관없이 모두 거룩하게 구별됐고, 음악을 맡은 레위인들도 다 있었지. 아삽, 헤만, 여두둔과 그 가족들로, 예배 예복을 입고 제단 동쪽에 모인 성가대와 관현악단에 나팔 부는 제사장 120명이 합류했어. 성가대와 나팔이 하나님을 향한 찬양과 감사의 한 목소리를 냈지. 관현악과 성가대가 완벽한 하모니로 하나님 찬양을 노래하고 연주했어. “그래! 하나님은 선하시다! 그의 변함없는 사랑은 영원하다!”'},
{'badge': '13-14', 'mr': '13-14',
 'en': "Then a billowing cloud filled The Temple of God. The priests couldn't even carry out their duties because of the cloud — the glory of God! — that filled The Temple of God.",
 'ko': '그러자 자욱한 구름이 하나님의 성전을 가득 채웠어. 성전을 가득 채운 그 구름, 하나님의 영광 때문에 제사장들은 자기 임무를 수행할 수조차 없었지.'},
], 'splits': [{'msg_range': '13', 'paras': [5, 6], 'note': "MSG 자체 문단 경계가 13절을 가름: [11-13]은 찬양('made one voice of praise and thanks to God')에서 끝나고, [13-14]은 'Then a billowing cloud filled The Temple of God'에서 시작. Teenz도 MSG 경계 그대로 유지. 편집적 split 아님."}], 'changes': ['초벌 작성 (MSG 5장 6문단 1:1 매핑; MSG 대조 완료)']},
6: {'title_en': "Solomon's Great Prayer", 'title_ko': '솔로몬의 위대한 기도', 'units': [
{'badge': '1-2', 'mr': '1-2', 'header_en': "Solomon's Dedication and Prayer", 'header_ko': '솔로몬의 봉헌과 기도',
 'en': 'Then Solomon said, God said he would dwell in a cloud, But I\'ve built a temple most splendid, A place for you to live in forever.',
 'ko': '그러고 나서 솔로몬이 말했어. “하나님은 구름 속에 거하겠다고 하셨지만, 저는 가장 화려한 성전을 지었습니다. 영원히 거하실 처소로요.”'},
{'badge': '3', 'mr': '3',
 'en': "The king then turned to face the congregation that had come together and blessed them:",
 'ko': '그러고 나서 왕이 모인 회중을 향해 돌아서서 그들을 축복했어.'},
{'badge': '4-6', 'mr': '4-6',
 'en': '"Blessed be God, the God of Israel, who spoke personally to my father David. Now he has done what he promised when he said, \'From the day I brought my people Israel up from Egypt, I haven\'t set apart one city among the tribes of Israel in which to build a temple to honor my Name, or chosen one person to be the leader. But now I have chosen both a city and a person: Jerusalem for honoring my Name and David to lead my people Israel.\'"',
 'ko': '“아버지 다윗에게 직접 말씀하신 이스라엘의 하나님을 찬양합니다. 이렇게 말씀하실 때 약속하신 것을 이제 이루셨습니다. ‘내 백성 이스라엘을 애굽에서 데려오던 날부터 이스라엘 지파들 가운데 내 이름을 기릴 성전을 지을 한 성읍도 구별하지 않았고, 지도자가 될 한 사람도 택하지 않았다. 그러나 이제 성과 사람을 택했다. 내 이름을 기릴 예루살렘과 내 백성 이스라엘을 이끌 다윗을.’”'},
{'badge': '7-9', 'mr': '7-9',
 'en': '"My father David very much wanted to build a temple honoring the Name of God, the God of Israel, but God told him, \'It was good that you wanted to build a temple in my honor — most commendable! But you are not the one to do it. Your son, who will carry on your dynasty, will build it for my Name.\'"',
 'ko': '“아버지 다윗은 이스라엘의 하나님 이름을 기리는 성전을 짓고 싶어 하셨습니다. 하지만 하나님이 이렇게 말씀하셨죠. ‘내 이름을 기리는 성전을 짓고 싶어 한 건 잘한 일이다. 정말 칭찬할 만해! 하지만 네가 지을 게 아니다. 왕조를 이을 네 아들이 내 이름을 위해 지을 것이다.’”'},
{'badge': '10-11', 'mr': '10-11',
 'en': '"And now you see the promise completed. God has done what he said he would do; I have succeeded David my father and now rule Israel; and I have built a temple to honor God, the God of Israel, and have secured a place for the Chest that holds the Covenant of God, the covenant he made with the people of Israel."',
 'ko': '“그리고 이제 약속이 이루어진 걸 봅니다. 하나님이 말씀하신 대로 행하셨어요. 제가 아버지 다윗을 이어 이제 이스라엘을 다스리고, 이스라엘의 하나님을 기리는 성전을 지었으며, 하나님의 언약, 곧 이스라엘 백성과 맺으신 언약을 담은 궤를 둘 자리를 마련했습니다.”'},
{'badge': '12-16', 'mr': '12-16',
 'en': "Before the entire congregation of Israel, Solomon took his position at the Altar of God and stretched out his hands. Solomon had made a bronze dais seven and a half feet square and four and a half feet high and placed it inside the court; that's where he now stood. Then he knelt in full view of the whole congregation, stretched his hands to heaven, and prayed: God, O God of Israel, there is no God like you in the skies above or on the earth below, who unswervingly keeps covenant with his servants and unfailingly loves them while they sincerely live in obedience to your way. You kept your word to David my father, your promise. You did exactly what you promised — every detail. The proof is before us today! Keep it up, God, O God of Israel! Continue to keep the promises you made to David my father when you said, \"You'll always have a descendant to represent my rule on Israel's throne, on the one condition that your sons are as careful to live obediently in my presence as you have.\"",
 'ko': '온 이스라엘 회중 앞에서 솔로몬이 하나님의 제단 앞에 자리를 잡고 손을 펼쳤어. 솔로몬은 가로세로 7.5피트, 높이 4.5피트인 놋 단상을 만들어 뜰 안에 두었는데, 지금 서 있는 곳이 바로 거기였지. 그러고 나서 온 회중이 보는 앞에서 무릎을 꿇고 하늘을 향해 손을 펼친 채 기도했어. “이스라엘의 하나님, 하나님! 위 하늘에도 아래 땅에도 당신 같은 신은 없습니다. 종들과 한결같이 언약을 지키시고, 그들이 진심으로 당신의 길에 순종하며 살 때 변함없이 사랑하시는 분. 아버지 다윗에게 하신 말씀, 약속을 지키셨습니다. 약속하신 그대로, 한 치도 어김없이 행하셨습니다. 증거가 오늘 우리 앞에 있습니다! 계속 그렇게 해주세요, 하나님, 이스라엘의 하나님! 아버지 다윗에게 하신 약속을 계속 지켜주세요. ‘네 아들들이 네가 그랬던 것처럼 내 앞에서 조심스럽게 순종하며 살기만 하면, 이스라엘 왕좌에서 내 다스림을 대신할 네 자손이 끊이지 않을 것이다’라고 하셨잖아요.”'},
{'badge': '17', 'mr': '17',
 'en': "O God, God of Israel, let this all happen — confirm and establish it!",
 'ko': '“하나님, 이스라엘의 하나님, 이 모든 일이 이루어지게 해주세요. 확정하시고 세워주세요!”'},
{'badge': '18-21', 'mr': '18-21',
 'en': "Can it be that God will actually move into our neighborhood? Why, the cosmos itself isn't large enough to give you breathing room, let alone this Temple I've built. Even so, I'm bold to ask: Pay attention to these my prayers, both intercessory and personal, O God, my God. Listen to my prayers, energetic and devout, that I'm setting before you right now. Keep your eyes open to this Temple day and night, this place you promised to dignify with your Name. And listen to the prayers that I pray in this place. And listen to your people Israel when they pray at this place. Listen from your home in heaven and when you hear, forgive.",
 'ko': '“하나님이 정말 우리 동네로 이사 오실 수 있겠습니까? 온 우주조차 당신께 숨 쉴 틈을 드리기엔 좁은데, 제가 지은 이 성전이야 말할 것도 없죠. 그래도 담대히 구합니다. 중보의 기도든 개인의 기도든, 제 기도에 귀 기울여주세요. 하나님, 저의 하나님. 지금 당신 앞에 드리는 열정적이고 경건한 제 기도를 들어주세요. 밤낮으로 이 성전을 눈여겨봐 주세요. 당신의 이름으로 영화롭게 하겠다고 약속하신 이곳을요. 그리고 제가 이곳에서 드리는 기도를 들어주세요. 당신의 백성 이스라엘이 이곳에서 기도할 때도 들어주세요. 하늘의 거처에서 들으시고, 들으시면 용서해주세요.”'},
{'badge': '22', 'mr': '22',
 'en': "When someone hurts a neighbor and promises to make things right, and then comes and repeats the promise before your Altar in this Temple,",
 'ko': '“누가 이웃에게 해를 끼치고 바로잡겠다고 약속한 뒤에 이 성전의 제단 앞에서 그 약속을 다시 되풀이하면,”'},
{'badge': '23', 'mr': '23',
 'en': "Listen from heaven and act; judge your servants, making the offender pay for the offense And set the offended free, dismissing all charges.",
 'ko': '“하늘에서 들으시고 행하소서. 종들을 재판하사, 가해자는 그 죄값을 치르게 하시고, 피해자는 풀어주시어 모든 혐의를 벗겨주소서.”'},
{'badge': '24-25', 'mr': '24-25',
 'en': "When your people Israel are beaten by an enemy because they've sinned against you, but then turn to you and acknowledge your rule in prayers desperate and devout in this Temple, Listen from your home in heaven; forgive the sin of your people Israel, return them to the land you gave to them and their ancestors.",
 'ko': '“당신의 백성 이스라엘이 당신께 죄를 지어 적에게 패했다가, 돌이켜 이 성전에서 필사적이고 경건한 기도로 당신의 다스림을 인정하면, 하늘의 거처에서 들으시고, 당신의 백성 이스라엘의 죄를 용서하시어 그들과 조상들에게 주신 땅으로 돌려보내주소서.”'},
{'badge': '26-27', 'mr': '26-27',
 'en': "When the skies shrivel up and there is no rain because your people have sinned against you, but then they pray at this place, acknowledging your rule and quit their sins because you have scourged them, Listen from your home in heaven, forgive the sins of your servants, your people Israel. Then start over with them; train them to live right and well; Send rain on the land you gave as inheritance to your people.",
 'ko': '“백성이 당신께 죄를 지어 하늘이 메마르고 비가 오지 않다가, 이곳에서 기도하며 당신의 다스림을 인정하고, 당신이 매를 드셨기 때문에 죄를 그만두면, 하늘의 거처에서 들으시고 종들, 당신의 백성 이스라엘의 죄를 용서해주소서. 그리고 그들과 다시 시작하소서. 바르고 선하게 사는 법을 가르치시고, 백성의 유산으로 주신 땅에 비를 내려주소서.”'},
{'badge': '28-31', 'mr': '28-31',
 'en': "When disasters strike, famine or catastrophe, crop failure or disease, locust or beetle, or when an enemy attacks their defenses — calamity of any sort — any prayer that's prayed from anyone at all among your people Israel, their hearts penetrated by disaster, hands and arms thrown out for help to this Temple, Listen from your home in heaven, forgive and reward us: reward each life and circumstance, For you know each life from the inside, (you're the only one with such inside knowledge!), So they'll live before you in lifelong reverence and believing obedience on this land you gave our ancestors.",
 'ko': '“재난이 닥칠 때, 기근이든 재앙이든, 흉작이든 질병이든, 메뚜기든 벌레든, 적이 방어선을 공격하든, 어떤 재난이든, 당신의 백성 이스라엘 중 누구든 드리는 기도, 재난에 마음이 꿰뚫리고 이 성전을 향해 도움의 손과 팔을 내미는 기도라면, 하늘의 거처에서 들으시고 용서하시며 우리에게 갚아주소서. 각 인생과 처지에 맞게 갚아주소서. 당신은 각 인생을 속속들이 아시니까요(그런 속 지식을 가진 분은 당신뿐!). 그러면 조상들에게 주신 이 땅에서 당신 앞에서 평생 경외하고 믿음으로 순종하며 살 것입니다.”'},
{'badge': '32', 'mr': '32',
 'en': "And don't forget the foreigner who is not a member of your people Israel but has come from a far country because of your reputation — people are going to be attracted here by your great reputation, your wonderworking power — and who come to pray to this Temple.",
 'ko': '“당신의 백성 이스라엘에 속하지 않았지만 당신의 명성 때문에 먼 나라에서 온 외국인도 잊지 마소서. 당신의 위대한 명성, 놀라운 능력 때문에 사람들이 여기로 끌려올 겁니다. 이 성전에 와서 기도하는 사람들을요.”'},
{'badge': '33', 'mr': '33',
 'en': "Listen from your home in heaven and honor the prayers of the foreigner, So that people all over the world will know who you are and what you're like, And live in reverent obedience before you, just as your own people Israel do, So they'll know that you personally make this Temple that I've built what it is.",
 'ko': '“하늘의 거처에서 들으시고 외국인의 기도를 이루어주소서. 온 세상 사람들이 당신이 누구시며 어떤 분인지 알게 하시고, 당신의 백성 이스라엘처럼 당신 앞에서 경외하며 순종하게 하소서. 제가 지은 이 성전을 당신께서 직접 당신의 것으로 만드셨다는 걸 알게 하소서.”'},
{'badge': '34-35', 'mr': '34-35',
 'en': "When your people go to war against their enemies at the time and place you send them and they pray to God toward the city you chose and The Temple I've built to honor your Name, Listen from heaven to what they pray and ask for and do what is right for them.",
 'ko': '“당신의 백성이 당신이 보내시는 때와 장소에 적과 전쟁하러 나가서, 당신이 택하신 성과 당신의 이름을 기리려고 제가 지은 성전을 향해 하나님께 기도하면, 하늘에서 그들이 기도하고 구하는 것을 들으시고 그들에게 옳은 일을 행해주소서.”'},
{'badge': '36-39', 'mr': '36-39',
 'en': 'When they sin against you — and they certainly will; there\'s no one without sin! — and in anger you turn them over to the enemy and they are taken captive to the enemy\'s land, whether far or near, but repent in the country of their captivity and pray with changed hearts in their exile, "We\'ve sinned; we\'ve done wrong; we\'ve been most wicked," and turn back to you heart and soul in the land of the enemy who conquered them, and pray to you toward their homeland, the land you gave their ancestors, toward the city you chose, and this Temple I have built to the honor of your Name, Listen from your home in heaven to their prayers desperate and devout; Do what is best for them. Forgive your people who have sinned against you.',
 'ko': '“그들이 당신께 죄를 지으면 — 분명 그럴 겁니다. 죄 없는 사람은 없으니까요! — 당신이 노하셔서 적에게 넘기시고 그들이 멀든 가깝든 적의 땅에 사로잡혀 가더라도, 포로 된 나라에서 회개하고 유배지에서 바뀐 마음으로 기도하며 “우리가 죄를 지었습니다. 잘못했습니다. 심히 악하게 행했습니다”라고 하고, 그들을 정복한 적의 땅에서 마음과 영혼을 다해 당신께 돌아와, 조상들에게 주신 고향 땅, 당신이 택하신 성, 당신의 이름을 기리려고 제가 지은 이 성전을 향해 당신께 기도하면, 하늘의 거처에서 그들의 필사적이고 경건한 기도를 들으시고, 그들에게 가장 좋은 것을 행해주소서. 당신께 죄 지은 당신의 백성을 용서해주소서.”'},
{'badge': '40', 'mr': '40',
 'en': "And now, dear God, be alert and attentive to prayer, all prayer, offered in this place.",
 'ko': '“그리고 이제 사랑하는 하나님, 이곳에서 드리는 모든 기도에 깨어 귀 기울여주소서.”'},
{'badge': '41-42', 'mr': '41-42',
 'en': "Up, God, enjoy your new place of quiet repose, you and your mighty covenant Chest; Dress your priests up in salvation clothes, let your holy people celebrate goodness. And don't, God, back out on your anointed ones, keep in mind the love promised to David your servant.",
 'ko': '“일어나소서, 하나님. 당신과 당신의 능하신 언약궤가 고요한 안식의 새 처소를 누리소서. 제사장들에게 구원의 옷을 입히시고, 거룩한 백성이 선을 축하하게 하소서. 하나님, 기름 부음 받은 자들을 저버리지 마시고, 종 다윗에게 약속하신 사랑을 기억해주소서.”'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 6장 19문단 1:1 매핑; MSG 대조 완료)']},
7: {'title_en': 'Fire Falls on the Temple', 'title_ko': '성전에 불이 내리다', 'units': [
{'badge': '1-3', 'mr': '1-3', 'header_en': 'The Temple Dedication', 'header_ko': '성전 봉헌',
 'en': "When Solomon finished praying, a bolt of lightning out of heaven struck the Whole-Burnt-Offering and sacrifices and the Glory of God filled The Temple. The Glory was so dense that the priests couldn't get in — God so filled The Temple that there was no room for the priests! When all Israel saw the fire fall from heaven and the Glory of God fill The Temple, they fell on their knees, bowed their heads, and worshiped, thanking God: Yes! God is good! His love never quits!",
 'ko': '솔로몬이 기도를 마치자 하늘에서 번개가 번쩍 내려와 번제와 제물을 삼키고 하나님의 영광이 성전을 가득 채웠어. 영광이 너무 짙어서 제사장들이 들어갈 수조차 없었지. 하나님이 성전을 가득 채우셔서 제사장들이 있을 자리가 없었어! 온 이스라엘이 하늘에서 불이 떨어지고 하나님의 영광이 성전을 채우는 걸 보고 무릎을 꿇고 머리를 숙여 예배하며 하나님께 감사했어. “그래! 하나님은 선하시다! 그의 사랑은 절대 끝나지 않는다!”'},
{'badge': '4-6', 'mr': '4-6',
 'en': "Then the king and all Israel worshiped, offering sacrifices to God. King Solomon worshiped by sacrificing 22,000 cattle and 120,000 sheep at the dedication of The Temple. The priests were all on duty; the choir and orchestra of Levites that David had provided for singing and playing anthems to the praise and love of God were all there; across the courtyard the priests blew trumpets. All Israelites were on their feet.",
 'ko': '그러고 나서 왕과 온 이스라엘이 하나님께 제사를 드리며 예배했어. 솔로몬 왕은 성전 봉헌식에서 소 22,000마리와 양 120,000마리를 잡아 예배했지. 제사장들은 모두 임무 중이었고, 다윗이 하나님 찬양과 사랑의 찬송을 노래하고 연주하게 마련해준 레위인 성가대와 관현악단이 다 있었어. 뜰 건너편에서는 제사장들이 나팔을 불었고, 온 이스라엘 백성이 일어서 있었지.'},
{'badge': '7-10', 'mr': '7-10',
 'en': "Solomon set apart the central area of the courtyard in front of God's Temple for sacred use and there sacrificed the Whole-Burnt-Offerings, Grain-Offerings, and fat from the Peace-Offerings — the Bronze Altar was too small to handle all these offerings. This is how Solomon kept the great autumn Feast of Booths. For seven days there were people there all the way from the far northeast (the Entrance to Hamath) to the far southwest (the Brook of Egypt) — a huge congregation. They started out celebrating for seven days, and then did it for another seven days, a week for dedicating the Altar and another for the Feast itself — two solid weeks of celebration! On the twenty-third day of the seventh month Solomon dismissed his congregation. They left rejoicing, exuberant over all the good God had done for David and Solomon and his people Israel.",
 'ko': '솔로몬이 하나님의 성전 앞 뜰 한가운데를 거룩한 용도로 구별하고 거기서 번제와 곡물제와 화목제의 기름을 드렸어. 놋제단은 이 많은 제물을 감당하기엔 너무 작았거든. 솔로몬이 위대한 가을 초막절을 지킨 방식이 이랬어. 7일 동안 먼 동북쪽(하맛 어귀)부터 먼 남서쪽(애굽 시내)까지 온 사람들이 모였어. 어마어마한 회중이었지. 처음 7일을 축하한 뒤에 또 7일을 더 했어. 제단 봉헌에 한 주, 명절 자체에 한 주. 꼬박 2주간의 축제! 일곱째 달 23일에 솔로몬이 회중을 해산시켰어. 그들은 기뻐하며 떠났지. 하나님이 다윗과 솔로몬과 그의 백성 이스라엘에게 행하신 모든 선한 일을 생각하며 들떠서.'},
{'badge': '11', 'mr': '11', 'header_en': "God's Confirmation", 'header_ko': '하나님의 확증',
 'en': "Solomon completed building The Temple of God and the royal palace — the projects he had set his heart on doing. Everything was done — success! Satisfaction!",
 'ko': '솔로몬이 하나님의 성전과 왕궁 짓기를 마쳤어. 마음을 다해 하고 싶었던 일들이었지. 모든 게 끝났어. 성공! 만족!'},
{'badge': '12-18', 'mr': '12-18',
 'en': 'God appeared to Solomon that very night and said, "I accept your prayer; yes, I have chosen this place as a temple for sacrifice, a house of worship. If I ever shut off the supply of rain from the skies or order the locusts to eat the crops or send a plague on my people, and my people, my God-defined people, respond by humbling themselves, praying, seeking my presence, and turning their backs on their wicked lives, I\'ll be there ready for you: I\'ll listen from heaven, forgive their sins, and restore their land to health. From now on I\'m alert day and night to the prayers offered at this place. Believe me, I\'ve chosen and sanctified this Temple that you have built: My Name is stamped on it forever; my eyes are on it and my heart in it always. As for you, if you live in my presence as your father David lived, pure in heart and action, living the life I\'ve set out for you, attentively obedient to my guidance and judgments, then I\'ll back your kingly rule over Israel — make it a sure thing on a sure foundation. The same covenant guarantee I gave to David your father I\'m giving to you, namely, \'You can count on always having a descendant on Israel\'s throne.\'"',
 'ko': '그날 바로 그 밤에 하나님이 솔로몬에게 나타나셔서 말씀하셨어. “네 기도를 받았다. 그래, 이곳을 제사드리는 성전, 예배의 집으로 택했다. 내가 하늘에서 비를 막거나 메뚜기에게 곡식을 먹게 하거나 내 백성에게 전염병을 보내더라도, 내 백성, 곧 내 이름으로 불리는 내 백성이 스스로 겸손해지고 기도하며 내 얼굴을 구하고 악한 길에서 돌이키면, 내가 너희를 위해 준비하고 있을 것이다. 하늘에서 듣고 그들의 죄를 용서하며 그들의 땅을 회복시키겠다. 이제부터 이곳에서 드리는 기도에 밤낮으로 귀 기울이겠다. 믿어라. 네가 지은 이 성전을 택하고 거룩하게 구별했다. 내 이름이 영원히 찍혀 있고, 내 눈이 그곳에, 내 마음이 항상 그 안에 있다. 너는 아버지 다윗이 살던 것처럼 내 앞에서 살면 된다. 마음과 행동이 순결하게, 내가 정해준 삶을 살고, 내 인도와 판단을 주의 깊게 순종하면, 이스라엘에 대한 네 왕권을 뒷받침하겠다. 확실한 토대 위에 확실하게 세우겠다. 아버지 다윗에게 준 그 언약의 보증을 너에게도 준다. 곧 ‘이스라엘 왕좌에 네 자손이 항상 있을 것을 믿어도 된다’는 것이다.”'},
{'badge': '19-22', 'mr': '19-22',
 'en': '"But if you or your sons betray me, ignoring my guidance and judgments, taking up with alien gods by serving and worshiping them, then the guarantee is off: I\'ll wipe Israel right off the map and repudiate this Temple I\'ve just sanctified to honor my Name. And Israel will be nothing but a bad joke among the peoples of the world. And this Temple, splendid as it now is, will become an object of contempt; tourists will shake their heads, saying, \'What happened here? What\'s the story behind these ruins?\' Then they\'ll be told, \'The people who used to live here betrayed their God, the very God who rescued their ancestors from Egypt; they took up with alien gods, worshiping and serving them. That\'s what\'s behind this God-visited devastation.\'"',
 'ko': '“하지만 너나 네 아들들이 나를 배신하고 내 인도와 판단을 무시하며, 다른 신들을 섬기고 경배하며 그들과 어울리면, 보증은 끝이다. 이스라엘을 지도에서 완전히 지워버리고, 내 이름을 기리려고 막 거룩하게 구별한 이 성전을 버리겠다. 그리고 이스라엘은 세상 민족들 사이에서 웃음거리에 불과하게 될 것이다. 지금은 웅장한 이 성전이 경멸의 대상이 될 것이다. 관광객들이 고개를 저으며 ‘여기 무슨 일이 있었던 거야? 이 폐허 뒤에 어떤 사연이 있는 거지?’라고 물을 것이다. 그러면 이렇게 대답해줄 것이다. ‘여기 살던 사람들이 자기들의 하나님을 배신했다. 조상들을 애굽에서 구해주신 바로 그 하나님을. 다른 신들과 어울려 섬기고 경배했다. 하나님이 찾아오셔서 황폐하게 하신 이유가 바로 그것이다.’”'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 7장 6문단 1:1 매핑; MSG 대조 완료)']},
8: {'title_en': "Solomon's Golden Years", 'title_ko': '솔로몬의 황금 시절', 'units': [
{'badge': '1-6', 'mr': '1-6', 'header_en': 'More on Solomon', 'header_ko': '솔로몬에 대한 이야기 더',
 'en': "At the end of twenty years, Solomon had quite a list of accomplishments. He had: built The Temple of God and his own palace; rebuilt the cities that Hiram had given him and colonized them with Israelites; marched on Hamath Zobah and took it; fortified Tadmor in the desert and all the store-cities he had founded in Hamath; built the fortress cities Upper Beth Horon and Lower Beth Horon, complete with walls, gates, and bars; built Baalath and store-cities; built chariot-cities for his horses. Solomon built impulsively and extravagantly — whenever a whim took him. And in Jerusalem, in Lebanon — wherever he fancied.",
 'ko': '20년이 끝나갈 무렵 솔로몬의 업적 목록은 꽤 길었어. 하나님의 성전과 자기 궁전을 지었고, 히람이 준 성읍들을 재건해서 이스라엘 사람을 이주시켰고, 하맛소바를 쳐서 점령했고, 사막의 다드몰과 하맛에 세운 모든 저장성들을 요새화했고, 성벽과 성문과 빗장을 갖춘 요새 성읍 윗벳호론과 아랫벳호론을 지었고, 바알랏과 저장성들을 지었고, 말들을 위한 전차 성읍들을 지었어. 솔로몬은 충동적으로, 호화롭게 지었어. 마음이 동할 때마다. 예루살렘에서도, 레바논에서도, 마음 가는 대로.'},
{'badge': '7-10', 'mr': '7-10',
 'en': "The remnants from the original inhabitants of the land (Hittites, Amorites, Perizzites, Hivites, Jebusites — all non-Israelites), survivors of the holy wars, were rounded up by Solomon for his gangs of slave labor. The policy is in effect today. But true Israelites were not treated this way; they were used in his army and administration — government leaders and commanders of his chariots and charioteers. They were also the project managers responsible for Solomon's building operations — 250 in all in charge of the workforce.",
 'ko': '그 땅 원래 주민들의 남은 자들(헷 사람, 아모리 사람, 브리스 사람, 히위 사람, 여부스 사람, 모두 비이스라엘인), 성전에서 살아남은 자들은 솔로몬이 노예 노동반으로 끌어모았어. 그 정책은 오늘날까지 시행 중이야. 하지만 진짜 이스라엘 백성은 그렇게 대하지 않았어. 군대와 행정에 썼지. 정부 지도자들과 전차와 마병의 지휘관들. 솔로몬의 건축 사업을 맡은 현장 감독도 그들이었어. 인력을 총괄하는 250명이었지.'},
{'badge': '11', 'mr': '11',
 'en': 'Solomon brought Pharaoh\'s daughter from the City of David to a house built especially for her, "Because," he said, "my wife cannot live in the house of David king of Israel, for the areas in which the Chest of God has entered are sacred."',
 'ko': '솔로몬이 바로의 딸을 다윗 성에서 그녀를 위해 특별히 지은 집으로 옮겼어. “아내가 이스라엘 왕 다윗의 집에 살 수 없기 때문”이라고 했지. “하나님의 궤가 들어간 곳들은 거룩하니까.”'},
{'badge': '12-13', 'mr': '12-13',
 'en': "Then Solomon offered Whole-Burnt-Offerings to God on the Altar of God that he had built in front of The Temple porch. He kept to the regular schedule of worship set down by Moses: Sabbaths, New Moons, and the three annual feasts of Unraised Bread (Passover), Weeks (Pentecost), and Booths.",
 'ko': '그러고 나서 솔로몬이 성전 현관 앞에 자기가 지은 하나님의 제단에서 하나님께 번제를 드렸어. 모세가 정해준 정규 예배 일정을 지켰지. 안식일, 초하루, 그리고 연 3대 명절인 무교절(유월절), 칠칠절(오순절), 초막절.'},
{'badge': '14-15', 'mr': '14-15',
 'en': "He followed the practice of his father David in setting up groups of priests carrying out the work of worship, with the Levites assigned to lead the sacred music for praising God and to assist the priests in the daily worship; he assigned security guards to be on duty at each gate — that's what David the man of God had ordered. The king's directions to the priests and Levites and financial stewards were kept right down to the fine print — no innovations — including the treasuries.",
 'ko': '아버지 다윗의 방식을 따라 예배 일을 맡을 제사장 조들을 세웠어. 레위인들은 하나님 찬양의 거룩한 음악을 이끌고 매일 예배에서 제사장들을 돕도록 배치했고, 각 문에는 경비병을 세웠지. 하나님의 사람 다윗이 명령한 그대로였어. 제사장과 레위인과 재무 관리들에게 내린 왕의 지시는 자잘한 부분까지 그대로 지켰어. 새로운 시도는 없었고, 곳간 관리까지 포함해서.'},
{'badge': '16', 'mr': '16',
 'en': "All that Solomon set out to do, from the groundbreaking of The Temple of God to its finish, was now complete.",
 'ko': '솔로몬이 착수한 모든 일, 하나님의 성전 첫 삽부터 완공까지가 이제 다 끝났어.'},
{'badge': '17-18', 'mr': '17-18',
 'en': "Then Solomon went to Ezion Geber and Elath on the coast of Edom. Hiram sent him ships and with them veteran sailors. Joined by Solomon's men they sailed to Ophir (in east Africa), loaded on fifteen tons of gold, and brought it back to King Solomon.",
 'ko': '그러고 나서 솔로몬이 에돔 해안의 에시온게벨과 엘랏으로 갔어. 히람이 배들을 보내줬는데 노련한 선원들과 함께였지. 솔로몬의 사람들과 합류해서 오빌(동아프리카)로 항해해 금 15톤을 싣고 솔로몬 왕에게 가져왔어.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 8장 7문단 1:1 매핑; MSG 대조 완료)']},
9: {'title_en': 'The Queen of Sheba Visits', 'title_ko': '스바 여왕의 방문', 'units': [
{'badge': '1-4', 'mr': '1-4',
 'en': "The queen of Sheba heard of Solomon's reputation and came to Jerusalem to put his reputation to the test, asking all the tough questions. She made a showy entrance — an impressive retinue of attendants and camels loaded with perfume and much gold and precious stones. She emptied her heart to Solomon, talking over everything she cared about. And Solomon answered everything she put to him — nothing stumped him. When the queen of Sheba experienced for herself Solomon's wisdom and saw with her own eyes the palace he had built, the meals that were served, the impressive array of court officials, the sharply dressed waiters, the cupbearers, and then the elaborate worship extravagant with Whole-Burnt-Offerings at The Temple of God, it all took her breath away.",
 'ko': '스바 여왕이 솔로몬의 명성을 듣고 예루살렘에 왔어. 어려운 질문들을 던지며 그 명성을 시험해보려는 거야. 등장은 화려했어. 수행원들의 위풍당당한 행렬과 향료, 많은 금, 보석을 실은 낙타들. 여왕은 솔로몬에게 마음을 다 털어놓으며 관심 있는 모든 걸 이야기했어. 솔로몬은 여왕이 내놓은 모든 질문에 답했지. 막히는 게 하나도 없었어. 스바 여왕이 솔로몬의 지혜를 직접 체험하고, 그가 지은 궁전, 차려지는 식사, 위풍당당한 신하들의 대열, 말쑥하게 차려입은 시종들, 술 관원들, 그리고 하나님의 성전에서 번제로 드리는 성대하고 화려한 예배까지 자기 눈으로 보자 숨이 멎을 지경이었어.'},
{'badge': '5-8', 'mr': '5-8',
 'en': 'She said to the king, "It\'s all true! Your reputation for accomplishment and wisdom that reached all the way to my country is confirmed. I wouldn\'t have believed it if I hadn\'t seen it for myself; they didn\'t exaggerate! Such wisdom and elegance — far more than I could ever have imagined. Lucky the men and women who work for you, getting to be around you every day and hear your wise words firsthand! And blessed be your God who has taken such a liking to you, making you king. Clearly, God\'s love for Israel is behind this, making you king to keep a just order and nurture a God-pleasing people."',
 'ko': '여왕이 왕에게 말했어. “전부 사실이네요! 제 나라까지 닿았던 당신의 업적과 지혜에 대한 명성이 확인됐어요. 직접 보지 못했으면 안 믿었을 거예요. 과장이 아니었네요! 이토록 지혜롭고 우아하시다니, 상상했던 것보다 훨씬 뛰어나세요. 당신 밑에서 일하는 남녀는 행운이에요. 매일 곁에 있으면서 지혜의 말씀을 직접 들을 수 있으니까요! 그리고 당신을 이토록 마음에 들어 하셔서 왕으로 세우신 당신의 하나님을 찬양합니다. 분명 하나님의 이스라엘 사랑이 이 뒤에 있어요. 공정한 질서를 지키고 하나님을 기쁘시게 하는 백성을 키우시려고 당신을 왕으로 세우신 거예요.”'},
{'badge': '9-11', 'mr': '9-11',
 'en': "She then gave the king four and a half tons of gold and sack after sack of spices and precious stones. There hasn't been a cargo of spices like the shipload the queen of Sheba brought to King Solomon. The ships of Hiram also imported gold from Ophir along with fragrant sandalwood and expensive gems. The king used the sandalwood for fine cabinetry in The Temple of God and the royal palace, and for making harps and dulcimers for the musicians. Nothing like that shipment of sandalwood has been seen since.",
 'ko': '그러고 나서 여왕이 왕에게 금 4.5톤과 자루에 자루를 이은 향료와 보석을 주었어. 스바 여왕이 솔로몬 왕에게 가져온 그 배 한 척 분의 향료 같은 화물은 전무후무했지. 히람의 배들도 오빌에서 금과 함께 향기로운 백단목과 값비싼 보석을 수입했어. 왕은 백단목을 하나님의 성전과 왕궁의 정교한 목공예에 쓰고, 음악가들을 위한 수금과 비파를 만드는 데 썼지. 그 백단목 화물 같은 건 그 뒤로 다시 본 적이 없어.'},
{'badge': '12', 'mr': '12',
 'en': "King Solomon, for his part, gave the queen of Sheba all her heart's desire — everything she asked for. She took away more than she brought. Satisfied, she returned home with her train of servants.",
 'ko': '솔로몬 왕은 그 답례로 스바 여왕이 마음에 원하는 모든 것, 구하는 모든 것을 주었어. 여왕은 가져온 것보다 더 많이 가져갔지. 만족한 채 수행원들을 이끌고 고향으로 돌아갔어.'},
{'badge': '13-14', 'mr': '13-14',
 'en': "Solomon received twenty-five tons of gold annually. This was above and beyond the taxes and profit on trade with merchants and traders. All kings of Arabia and various and assorted governors also brought silver and gold to Solomon.",
 'ko': '솔로몬은 매년 금 25톤을 받았어. 상인들과 무역으로 얻는 세금과 이익은 별도였지. 아라비아의 모든 왕들과 여러 총독들도 솔로몬에게 은금을 가져왔어.'},
{'badge': '15-16', 'mr': '15-16',
 'en': "King Solomon crafted two hundred body-length shields of hammered gold — about fifteen pounds of gold to each shield — and about three hundred small shields about half that size. He stored the shields in the House of the Forest of Lebanon.",
 'ko': '솔로몬 왕이 두드린 금으로 사람 키만 한 큰 방패 200개를 만들었어. 방패 하나에 금 약 15파운드. 그리고 그 절반 크기 정도의 작은 방패 300개도 만들었지. 방패들은 레바논 숲 궁에 보관했어.'},
{'badge': '17-19', 'mr': '17-19',
 'en': "The king made a massive throne of ivory with a veneer of gold. The throne had six steps leading up to it with an attached footstool of gold. The armrests on each side were flanked by lions. Lions, twelve of them, were placed at either end of the six steps. There was no throne like it in any other kingdom.",
 'ko': '왕이 상아에 금을 입힌 거대한 왕좌를 만들었어. 왕좌로 올라가는 계단이 여섯 개였고 금 발판이 붙어 있었지. 양쪽 팔걸이 옆에는 사자들이 서 있었어. 사자 열두 마리가 여섯 계단의 양쪽 끝에 놓였지. 어떤 나라에도 이런 왕좌는 없었어.'},
{'badge': '20', 'mr': '20',
 'en': "King Solomon's chalices and tankards were made of gold, and all the dinnerware and serving utensils in the House of the Forest of Lebanon were pure gold. Nothing was made of silver; silver was considered common and cheap in the time of Solomon.",
 'ko': '솔로몬 왕의 술잔과 물통은 금으로 만들었고, 레바논 숲 궁의 모든 식기와 서빙 기구는 순금이었어. 은으로 만든 건 하나도 없었지. 솔로몬 시대에는 은이 흔하고 값싼 취급을 받았거든.'},
{'badge': '21', 'mr': '21',
 'en': "The king's ships, manned by Hiram's sailors, made a round trip to Tarshish every three years, returning with a cargo of gold, silver, and ivory, apes and peacocks.",
 'ko': '히람의 선원들이 탄 왕의 배들이 3년마다 다시스로 왕복 항해했어. 금, 은, 상아, 원숭이, 공작을 싣고 돌아왔지.'},
{'badge': '22-24', 'mr': '22-24',
 'en': "King Solomon was richer and wiser than all the kings of the earth — he surpassed them all. Kings came from all over the world to be with Solomon and get in on the wisdom God had given him. Everyone who came brought gifts — artifacts of gold and silver, fashionable robes and gowns, the latest in weapons, exotic spices, horses, and mules — parades of visitors, year after year.",
 'ko': '솔로몬 왕은 땅의 모든 왕보다 부유하고 지혜로웠어. 모두를 능가했지. 온 세상 왕들이 솔로몬과 함께하려고, 하나님이 주신 지혜를 얻으려고 찾아왔어. 찾아오는 사람마다 선물을 가져왔지. 금은 기물, 멋진 예복과 가운, 최신 무기, 이국적인 향료, 말과 노새. 해마다 이어지는 방문객 행렬이었어.'},
{'badge': '25-28', 'mr': '25-28',
 'en': "Solomon collected horses and chariots. He had four thousand stalls for horses and chariots, and twelve thousand horsemen in barracks in the chariot-cities and in Jerusalem. He ruled over all the kings from the River Euphrates in the east, throughout the Philistine country, and as far west as the border of Egypt. The king made silver as common as rocks and cedar as common as the fig trees in the lowland hills. He carried on a brisk horse-trading business with Egypt and other places.",
 'ko': '솔로몬이 말과 전차를 모았어. 말과 전차용 외양간이 4,000칸이었고, 기병 12,000명이 전차 성읍들과 예루살렘의 병영에 있었지. 동쪽 유브라데 강에서 블레셋 땅을 거쳐 서쪽 애굽 국경까지 모든 왕들을 다스렸어. 왕은 은을 돌처럼 흔하게, 백향목을 저지대 언덕의 무화과나무처럼 흔하게 만들었지. 애굽과 다른 지역들과 활발한 말 무역을 했어.'},
{'badge': '29-31', 'mr': '29-31',
 'en': "The rest of Solomon's life and rule, from start to finish, one can read in the records of Nathan the prophet, the prophecy of Ahijah of Shiloh, and in the visions of Iddo the seer concerning Jeroboam son of Nebat. Solomon ruled in Jerusalem over all Israel for forty years. Solomon died and was buried in the City of David his father. His son Rehoboam was the next king.",
 'ko': '솔로몬의 나머지 생애와 통치, 처음부터 끝까지는 선지자 나단의 기록, 실로 사람 아히야의 예언, 느밧의 아들 여로보암에 관한 선견자 잇도의 묵시에서 볼 수 있어. 솔로몬이 예루살렘에서 온 이스라엘을 40년 동안 다스렸어. 솔로몬이 죽어 아버지 다윗의 성에 묻혔고, 아들 르호보암이 다음 왕이 됐지.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 9장 12문단 1:1 매핑; MSG 대조 완료)']},
10: {'title_en': "Rehoboam's Big Mistake", 'title_ko': '르호보암의 큰 실수', 'units': [
{'badge': '1-2', 'mr': '1-2', 'header_en': 'King Rehoboam', 'header_ko': '르호보암 왕',
 'en': "Rehoboam traveled to Shechem where all Israel had gathered to inaugurate him as king. Jeroboam was then in Egypt, where he had taken asylum from King Solomon; when he got the report of Solomon's death, he came back.",
 'ko': '르호보암이 세겜으로 갔어. 온 이스라엘이 그를 왕으로 세우려고 모인 곳이었지. 여로보암은 그때 애굽에 있었어. 솔로몬 왕을 피해 망명했던 곳. 솔로몬이 죽었다는 소식을 듣고 돌아왔지.'},
{'badge': '3-4', 'mr': '3-4',
 'en': 'Summoned by Israel, Jeroboam and all Israel went to Rehoboam and said, "Your father made life hard for us — worked our fingers to the bone. Give us a break; lighten up on us and we\'ll willingly serve you."',
 'ko': '이스라엘의 부름을 받은 여로보암과 온 이스라엘이 르호보암에게 가서 말했어. “아버님이 우리 삶을 힘들게 하셨어요. 뼈가 부서져라 일시켰죠. 숨 좀 돌리게 해주세요. 짐을 가볍게 해주시면 기꺼이 섬기겠습니다.”'},
{'badge': '5', 'mr': '5',
 'en': '"Give me," said Rehoboam, "three days to think it over; then come back." So the people left.',
 'ko': '르호보암이 말했어. “사흘 시간을 주시오. 생각해보고 다시 오시오.” 그래서 백성이 물러갔어.'},
{'badge': '6', 'mr': '6',
 'en': 'King Rehoboam talked it over with the elders who had advised his father when he was alive: "What\'s your counsel? How do you suggest that I answer the people?"',
 'ko': '르호보암 왕이 아버지가 살아 계실 때 조언하던 원로들과 상의했어. “어떻게 조언하시겠소? 백성에게 뭐라고 답하는 게 좋겠소?”'},
{'badge': '7', 'mr': '7',
 'en': 'They said, "If you will be a servant to this people, be considerate of their needs and respond with compassion, work things out with them, they\'ll end up doing anything for you."',
 'ko': '그들이 말했어. “이 백성의 종이 되어주십시오. 그들의 필요를 헤아리고 긍휼히 응답하며 그들과 잘 풀어가십시오. 그러면 그들이 당신을 위해 뭐든 하게 될 겁니다.”'},
{'badge': '8-9', 'mr': '8-9',
 'en': 'But he rejected the counsel of the elders and asked the young men he\'d grown up with who were now currying his favor, "What do you think? What should I say to these people who are saying, \'Give us a break from your father\'s harsh ways — lighten up on us\'?"',
 'ko': '하지만 그는 원로들의 조언을 물리치고, 함께 자라나 지금은 자기에게 아부하는 젊은이들에게 물었어. “너희는 어떻게 생각하니? ‘아버지의 가혹한 방식에서 숨 좀 돌리게 해달라, 짐을 가볍게 해달라’고 말하는 이 백성에게 뭐라고 해야겠니?”'},
{'badge': '10-11', 'mr': '10-11',
 'en': 'The young turks he\'d grown up with said, "These people who complain, \'Your father was too hard on us; lighten up\' — well, tell them this: \'My little finger is thicker than my father\'s waist. If you think life under my father was hard, you haven\'t seen the half of it. My father thrashed you with whips; I\'ll beat you bloody with chains!\'"',
 'ko': '함께 자란 젊은 패기들이 말했어. “‘아버지가 너무 가혹했다, 짐을 가볍게 해달라’고 불평하는 저 사람들 말이죠. 이렇게 말하세요. ‘내 새끼손가락이 아버지 허리보다 굵다. 아버지 때 삶이 힘들었다고 생각하면, 아직 반도 못 봤다. 아버지는 채찍으로 매질했지만, 나는 쇠사슬로 피투성이가 되도록 때리겠다!’”'},
{'badge': '12-14', 'mr': '12-14',
 'en': 'Three days later Jeroboam and the people showed up, just as Rehoboam had directed when he said, "Give me three days to think it over; then come back." The king\'s answer was harsh and rude. He spurned the counsel of the elders and went with the advice of the younger set: "If you think life under my father was hard, you haven\'t seen the half of it: my father thrashed you with whips; I\'ll beat you bloody with chains!"',
 'ko': '사흘 뒤 여로보암과 백성이 나타났어. 르호보암이 “사흘 시간을 달라, 그때 다시 오라”고 했던 그대로였지. 왕의 대답은 가혹하고 무례했어. 원로들의 조언을 차버리고 젊은 무리의 조언을 따랐지. “아버지 때 삶이 힘들었다고 생각하면 아직 반도 못 봤다. 아버지는 채찍으로 매질했지만, 나는 쇠사슬로 피투성이가 되도록 때리겠다!”'},
{'badge': '15', 'mr': '15',
 'en': "Rehoboam turned a deaf ear to the people. God was behind all this, confirming the message that he had given to Jeroboam son of Nebat through Ahijah of Shiloh.",
 'ko': '르호보암이 백성의 말에 귀를 닫았어. 이 모든 일 뒤에는 하나님이 계셨어. 실로 사람 아히야를 통해 느밧의 아들 여로보암에게 주셨던 말씀을 이루시려는 거야.'},
{'badge': '16-17', 'mr': '16-17',
 'en': "When all Israel realized that the king hadn't listened to a word they'd said, they stood up to him and said, Get lost, David! We've had it with you, son of Jesse! Let's get out of here, Israel, and fast! From now on, David, mind your own business. And with that they left. Rehoboam continued to rule only those who lived in the towns of Judah.",
 'ko': '온 이스라엘이 왕이 자기들 말을 한마디도 듣지 않았다는 걸 깨닫자 맞서서 말했어. “꺼져라, 다윗아! 진절머리 난다, 이새의 아들아! 이스라엘아, 여기서 빨리 나가자! 이제부터 다윗아, 네 일이나 신경 써라.” 그리고 그들은 떠났어. 르호보암은 유다 성읍들에 사는 사람들만 계속 다스렸지.'},
{'badge': '18-19', 'mr': '18-19',
 'en': "When King Rehoboam next sent out Adoniram, head of the workforce, the Israelites ganged up on him, pelted him with stones, and killed him. King Rehoboam jumped in his chariot and escaped to Jerusalem as fast as he could. Israel has been in rebellion against the Davidic dynasty ever since.",
 'ko': '르호보암 왕이 다음으로 역군 감독 아도니람을 보내자 이스라엘 사람들이 그에게 달려들어 돌을 던져 죽였어. 르호보암 왕은 전차에 뛰어올라 최대한 빨리 예루살렘으로 도망쳤지. 그 이후로 이스라엘은 다윗 왕조에 반역한 채 지금까지야.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 10장 11문단 1:1 매핑; MSG 대조 완료)']},
11: {'title_en': 'Rehoboam Fortifies Judah', 'title_ko': '르호보암, 유다를 요새화하다', 'units': [
{'badge': '1', 'mr': '1',
 'en': "When Rehoboam got back to Jerusalem he called up the men of the tribes of Judah and Benjamin, 180,000 of their best soldiers, to go to war against Israel and recover the kingdom.",
 'ko': '르호보암이 예루살렘으로 돌아오자 유다와 베냐민 지파의 남자들, 정예병 18만 명을 소집해서 이스라엘과 전쟁하고 왕국을 되찾으려 했어.'},
{'badge': '2-4', 'mr': '2-4',
 'en': 'At the same time the word of God came to Shemaiah, a holy man, "Tell this to Rehoboam son of Solomon, king of Judah, along with all the Israelites in Judah and Benjamin, This is God\'s word: Don\'t march out; don\'t fight against your brothers the Israelites. Go back home, every last one of you; I\'m in charge here." And they did it; they did what God said and went home.',
 'ko': '그때 하나님의 말씀하신 성자, 스마야에게 하나님의 말씀이 임했어. “솔로몬의 아들 유다 왕 르호보암과 유다와 베냐민에 있는 모든 이스라엘 사람에게 이렇게 전하여라. 하나님의 말씀이다. 출정하지 마라. 형제 이스라엘 사람들과 싸우지 마라. 한 사람도 빠짐없이 집으로 돌아가라. 내가 주관한다.” 그들이 그대로 했어. 하나님이 말씀하신 대로 하고 집으로 갔지.'},
{'badge': '5-12', 'mr': '5-12',
 'en': "Rehoboam continued to live in Jerusalem but built up a defense system for Judah all around: in Bethlehem, Etam, Tekoa, Beth Zur, Soco, Adullam, Gath, Mareshah, Ziph, Adoraim, Lachish, Azekah, Zorah, Aijalon, and Hebron — a line of defense protecting Judah and Benjamin. He beefed up the fortifications, appointed commanders, and put in supplies of food, olive oil, and wine. He installed arms — large shields and spears — in all the forts, making them very strong. So Judah and Benjamin were secure for the time.",
 'ko': '르호보암은 예루살렘에 계속 살면서 유다 방방곡곡에 방어 체계를 세웠어. 베들레헴, 에담, 드고아, 벧술, 소고, 아둘람, 가드, 마레사, 십, 아도라임, 라기스, 아세가, 소라, 아얄론, 헤브론. 유다와 베냐민을 지키는 방어선이었지. 요새를 튼튼히 하고 지휘관을 세우고 식량과 올리브유와 포도주를 비축했어. 모든 요새에 무기, 큰 방패와 창을 배치해서 아주 강하게 만들었지. 그래서 유다와 베냐민은 당분간 안전했어.'},
{'badge': '13-17', 'mr': '13-17',
 'en': "The priests and Levites from all over Israel came and made themselves available to Rehoboam. The Levites left their pastures and properties and moved to Judah and Jerusalem because Jeroboam and his sons had dismissed them from the priesthood of God and replaced them with his own priests to preside over the worship centers at which he had installed goat and calf demon-idols. Everyone from all the tribes of Israel who determined to seek the God of Israel migrated with the priests and Levites to Jerusalem to worship there, sacrificing to the God of their ancestors. That gave a tremendous boost to the kingdom of Judah. They stuck with Rehoboam son of Solomon for three years, loyal to the ways of David and Solomon for this period.",
 'ko': '온 이스라엘의 제사장들과 레위인들이 르호보암에게 와서 자신을 내주었어. 레위인들은 목장과 재산을 버리고 유다와 예루살렘으로 이주했지. 여로보암과 그 아들들이 그들을 하나님의 제사장직에서 해임하고, 염소와 송아지 귀신 우상을 세운 예배 처소들을 맡을 자기 제사장들로 교체했기 때문이야. 이스라엘의 하나님을 찾기로 작정한 모든 지파 사람들이 제사장, 레위인들과 함께 예루살렘으로 이주해서 거기서 예배했어. 조상들의 하나님께 제사드리면서. 유다 왕국에 엄청난 힘이 되었지. 그들은 솔로몬의 아들 르호보암과 3년 동안 함께했어. 이 기간 다윗과 솔로몬의 길에 충성하면서.'},
{'badge': '18-21', 'mr': '18-21',
 'en': "Rehoboam married Mahalath daughter of Jerimoth, David's son, and Abihail daughter of Eliab, Jesse's son. Mahalath bore him Jeush, Shemariah, and Zaham. Then he married Maacah, Absalom's daughter, and she bore him Abijah, Attai, Ziza, and Shelomith. Maacah was Rehoboam's favorite wife; he loved her more than all his other wives and concubines put together (and he had a lot — eighteen wives and sixty concubines who produced twenty-eight sons and sixty daughters!).",
 'ko': '르호보암은 다윗의 아들 여리못의 딸 마할랏과 이새의 아들 엘리압의 딸 아비하일과 결혼했어. 마할랏이 여우스, 스마랴, 사함을 낳았지. 그다음 압살롬의 딸 마아가와 결혼했는데, 그녀가 아비야, 앗대, 시사, 슬로밋을 낳았어. 마아가는 르호보암이 가장 사랑하는 아내였어. 다른 모든 아내와 첩을 합친 것보다 더 사랑했지(꽤 많았어. 아내 18명, 첩 60명이 아들 28명, 딸 60명을 낳았으니까!).'},
{'badge': '22-23', 'mr': '22-23',
 'en': 'Rehoboam designated Abijah son of Maacah as the "first son" and leader of the brothers — he intended to make him the next king. He was shrewd in deploying his sons in all the fortress cities that made up his defense system in Judah and Benjamin; he kept them happy with much food and many wives.',
 'ko': '르호보암이 마아가의 아들 아비야를 “맏아들”이자 형제들의 지도자로 지명했어. 다음 왕으로 세우려는 속셈이었지. 유다와 베냐민의 방어 체계를 이루는 모든 요새 성읍에 아들들을 배치하는 데는 영리했어. 넉넉한 식량과 많은 아내들로 그들을 만족시켜주었지.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 11장 6문단 1:1 매핑; MSG 대조 완료)']},
12: {'title_en': 'Shishak Attacks Jerusalem', 'title_ko': '시삭이 예루살렘을 치다', 'units': [
{'badge': '1', 'mr': '1',
 'en': "By the time Rehoboam had secured his kingdom and was strong again, he, and all Israel with him, had virtually abandoned God and his ways.",
 'ko': '르호보암이 왕국을 굳게 세우고 다시 강해졌을 때쯤, 그와 함께한 온 이스라엘이 하나님과 그의 길을 사실상 버렸어.'},
{'badge': '2-4', 'mr': '2-4',
 'en': "In Rehoboam's fifth year, because he and the people were unfaithful to God, Shishak king of Egypt invaded as far as Jerusalem. He came with twelve hundred chariots and sixty thousand cavalry, and soldiers from all over — the Egyptian army included Libyans, Sukkites, and Ethiopians. They took the fortress cities of Judah and advanced as far as Jerusalem itself.",
 'ko': '르호보암 5년에, 그와 백성이 하나님께 불충했기 때문에 애굽 왕 시삭이 예루살렘까지 쳐들어왔어. 전차 1,200대와 기병 6만 명을 이끌고, 사방에서 온 병사들과 함께였지. 애굽 군대에는 리비아 사람, 숙 사람, 구스 사람도 포함됐어. 유다의 요새 성읍들을 빼앗고 예루살렘 자체까지 진격했지.'},
{'badge': '5', 'mr': '5',
 'en': 'Then the prophet Shemaiah, accompanied by the leaders of Judah who had retreated to Jerusalem before Shishak, came to Rehoboam and said, "God\'s word: You abandoned me; now I abandon you to Shishak."',
 'ko': '그러고 나서 선지자 스마야가 시삭 앞에서 예루살렘으로 후퇴한 유다 지도자들과 함께 르호보암에게 와서 말했어. “하나님의 말씀. 너희가 나를 버렸으니, 이제 내가 너희를 시삭에게 버린다.”'},
{'badge': '6', 'mr': '6',
 'en': 'The leaders of Israel and the king were repentant and said, "God is right."',
 'ko': '이스라엘의 지도자들과 왕이 뉘우치며 말했어. “하나님이 옳으시다.”'},
{'badge': '7-8', 'mr': '7-8',
 'en': 'When God saw that they were humbly repentant, the word of God came to Shemaiah: "Because they are humble, I\'ll not destroy them — I\'ll give them a break; I won\'t use Shishak to express my wrath against Jerusalem. What I will do, though, is make them Shishak\'s subjects — they\'ll learn the difference between serving me and serving human kings."',
 'ko': '하나님이 그들이 겸손히 뉘우치는 걸 보시고 스마야에게 하나님의 말씀이 임했어. “그들이 겸손하니 멸하지 않겠다. 숨 돌릴 틈을 주겠다. 시삭을 통해 예루살렘에 대한 내 진노를 표출하지 않겠다. 하지만 이렇게 하겠다. 그들을 시삭의 신하로 만들겠다. 나를 섬기는 것과 사람의 왕을 섬기는 것의 차이를 배우게 될 것이다.”'},
{'badge': '9', 'mr': '9',
 'en': "Then Shishak king of Egypt attacked Jerusalem. He plundered the treasury of The Temple of God and the treasury of the royal palace — he took everything he could lay his hands on. He even took the gold shields that Solomon had made.",
 'ko': '그러고 나서 애굽 왕 시삭이 예루살렘을 쳤어. 하나님의 성전 곳간과 왕궁 곳간을 약탈했지. 손에 닿는 건 다 가져갔어. 솔로몬이 만든 금 방패들까지 가져갔지.'},
{'badge': '10-11', 'mr': '10-11',
 'en': "King Rehoboam replaced the gold shields with bronze shields and gave them to the guards who were posted at the entrance to the royal palace. Whenever the king went to God's Temple, the guards went with him carrying the shields, but they always returned them to the guardroom.",
 'ko': '르호보암 왕이 금 방패 대신 놋 방패를 만들어 왕궁 입구에 서 있는 경비병들에게 맡겼어. 왕이 하나님의 성전에 갈 때마다 경비병들이 방패를 들고 함께 갔지만, 항상 경비실로 돌려놓았지.'},
{'badge': '12', 'mr': '12',
 'en': "Because Rehoboam was repentant, God's anger was blunted, so he wasn't totally destroyed. The picture wasn't entirely bleak — there were some good things going on in Judah.",
 'ko': '르호보암이 뉘우쳤기 때문에 하나님의 분노가 누그러져서 완전히 멸망하지는 않았어. 상황이 완전히 암담했던 건 아니야. 유다에는 좋은 일들도 좀 있었거든.'},
{'badge': '13-14', 'mr': '13-14',
 'en': "King Rehoboam regrouped and reestablished his rule in Jerusalem. He was forty-one years old when he became king and continued as king for seventeen years in Jerusalem, the city God chose out of all the tribes of Israel as the special presence of his Name. His mother was Naamah from Ammon. But the final verdict on Rehoboam was that he was a bad king — God was not important to him; his heart neither cared for nor sought after God.",
 'ko': '르호보암 왕이 전열을 정비하고 예루살렘에서 통치를 다시 세웠어. 왕이 될 때 41살이었고, 하나님이 이스라엘 모든 지파 가운데 자기 이름의 특별한 임재처로 택하신 성 예루살렘에서 17년 동안 왕으로 있었지. 어머니는 암몬 출신 나아마였어. 하지만 르호보암에 대한 최종 평가는 나쁜 왕이었다는 거야. 하나님이 그에게 중요하지 않았어. 그의 마음은 하나님을 돌보지도 찾지도 않았지.'},
{'badge': '15-16', 'mr': '15-16',
 'en': "The history of Rehoboam, from start to finish, is written in the memoirs of Shemaiah the prophet and Iddo the seer that contain the family trees. There was war between Rehoboam and Jeroboam the whole time. Rehoboam died and was buried with his ancestors in the City of David. His son Abijah ruled after him.",
 'ko': '르호보암의 역사, 처음부터 끝까지는 족보들을 담은 선지자 스마야와 선견자 잇도의 회고록에 기록되어 있어. 르호보암과 여로보암 사이에는 내내 전쟁이 있었지. 르호보암이 죽어 조상들과 함께 다윗 성에 묻혔어. 아들 아비야가 뒤를 이어 다스렸지.'},
], 'splits': [], 'changes': ['초벌 작성 (MSG 12장 10문단 1:1 매핑; MSG 대조 완료)']},
}
