# -*- coding: utf-8 -*-
"""2Chronicles ch21-25 teen EN/KO (작업자 D2, MSG 직역 기반 초벌)."""
CHAPTERS = {
21: {
 "title_en": "Jehoram's Wicked Reign",
 "title_ko": "여호람의 악한 통치",
 "units": [
  {"badge":"1-4","mr":"1-4",
   "en":"Jehoshaphat died and was buried with his ancestors in the City of David. Jehoram, his son, became king in his place. He had brothers, sons of Jehoshaphat: Azariah, Jehiel, Zechariah, Azariahu, Michael, and Shephatiah \u2014 all sons of Jehoshaphat, king of Judah. Their father had given them valuable gifts, including silver, gold, and other valuables, along with fortress cities in Judah. But he gave the kingdom to Jehoram because he was the oldest. But when Jehoram had taken over his father's kingdom and had secured his position, he killed all his brothers, and a number of the leaders of Israel besides.",
   "ko":"여호사밧이 죽어 다윗 성에 조상들과 함께 묻혔어. 아들 여호람이 왕이 됐지. 여호사밧의 아들인 형제들이 있었어. 아사랴, 여히엘, 스가랴, 아사랴후, 미가엘, 스바댜 \u2014 모두 유다 왕 여호사밧의 아들들이야. 아버지가 은과 금과 귀중품 등 값진 선물을 주셨고, 유다의 요새 성읍들도 주셨지. 하지만 나라는 여호람에게 주셨어. 맏아들이었거든. 그런데 여호람이 아버지의 나라를 물려받아 자리를 굳히자마자 모든 형제를 죽이고, 이스라엘 지도자 몇 명도 함께 죽였어."},
  {"badge":"5-6","mr":"5-6",
   "en":"Jehoram was thirty-two years old when he became king and ruled in Jerusalem for eight years. He lived badly, following the example of the kings of Israel and Ahab's family \u2014 he married a daughter of Ahab! \u2014 doing evil in the eyes of God.",
   "ko":"여호람은 왕이 될 때 32살이었고 예루살렘에서 8년 동안 다스렸어. 나쁘게 살았지. 이스라엘 왕들과 아합 집안을 본받아 \u2014 아합의 딸과 결혼했거든! \u2014 하나님 눈에 악을 행했어."},
  {"badge":"7","mr":"7",
   "en":"But God was not about to destroy the family of David because of his promise to David \u2014 he had promised David, and his descendants, a ruling light forever.",
   "ko":"하지만 하나님은 다윗에게 하신 약속 때문에 다윗 가문을 멸하려 하지 않으셨어. 다윗과 그 자손에게 영원히 다스리는 빛을 약속하셨으니까."},
  {"badge":"8-11","mr":"8-11",
   "en":"During Jehoram's time, Edom broke away from Judah, elected a king, and set up their own independent kingdom. Jehoram took his chariot commanders and all his chariots and marched on Edom by night. The Edomites surrounded him and his chariot commanders, but he managed to get away. Edom continues in revolt against Judah right up to the present. Even little Libnah revolted at that time. The reasons were many, but mostly because he abandoned the God of his ancestors. Jehoram also built neighborhood sex-and-religion shrines \u2014 one in every city \u2014 and turned the life of Jerusalem into one long orgy, seducing Judah.",
   "ko":"여호람 시대에 에돔이 유다에서 떨어져 나와 왕을 선출하고 독립 왕국을 세웠어. 여호람이 전차 지휘관들과 모든 전차를 이끌고 밤에 에돔으로 진격했지. 에돔 사람들이 그와 전차 지휘관들을 포위했지만, 겨우 빠져나왔어. 에돔은 지금까지도 유다에 대한 반역을 계속하고 있어. 작은 립나도 그때 반역했지. 이유는 많았지만, 주로 조상들의 하나님을 버렸기 때문이야. 여호사밧이 세운 동네 음란 종교 산당도 하나. 모든 성읍에 하나씩. 예루살렘의 삶을 긴 난잡한 파티로 만들고 유다를 꾀었지."},
  {"badge":"12-15","mr":"12-15",
   "en":"Then he got a letter from Elijah the prophet. It said: \u201cThis is what God, the God of David your ancestor, says: You haven't kept to the ways of your father Jehoshaphat and your grandfather Asa, kings of Judah. Instead you've taken up the ways of the kings of Israel in the north, leading Judah and Jerusalem away from God \u2014 going step by step down the apostate path of Ahab and his crew. You've killed your own brothers, your own family \u2014 better men than you! And now you're about to pay the price: God is going to hit your people, your children, your wives, and all your property with a terrible plague. And that's just the beginning \u2014 you're going to get a terrible disease of the colon, in which you'll need a colostomy bag for the rest of your life.\u201d",
   "ko":"그러자 선지자 엘리야에게서 편지가 왔어. 이렇게 쓰여 있었지. \u201c네 조상 다윗의 하나님께서 이렇게 말씀하신다. 네 아버지 여호사밧과 네 할아버지 아사, 유다 왕들의 길을 지키지 않았다. 대신 북쪽 이스라엘 왕들의 길을 따라 유다와 예루살렘을 하나님에게서 떠나게 했다 \u2014 아합과 그 무리의 배도 길을 한 걸음씩 따라가며. 네 형제들, 네 가족 \u2014 너보다 나은 사람들 \u2014 을 죽였다. 이제 값을 치르게 될 거다. 하나님이 네 백성, 네 자식, 네 아내들, 네 모든 재산을 끔찍한 재앙으로 치실 거다. 그게 시작에 불과하다 \u2014 너는 대장에 끔찍한 병이 걸려 평생 결장루 주머니를 차고 살아야 할 거다.\u201d"},
  {"badge":"16-18","mr":"16-18",
   "en":"God had a new purpose for Jehoram \u2014 to give him a taste of his own medicine. He stirred up the Philistines and the Arabs who lived near the Ethiopians against Jehoram. They attacked Judah, breached the city walls, and carried off everything they could find in the king's palace \u2014 even his children and wives! The only one left was Ahaziah, his youngest son.",
   "ko":"하나님이 여호람에게 새로운 뜻을 두셨어. 제 약을 맛보게 하려는 거야. 에티오피아 사람들 근처에 살던 블레셋 사람과 아라비아 사람을 여호람에게 대항해 일으키셨지. 그들이 유다를 공격해 성벽을 뚫고 왕궁에서 찾을 수 있는 모든 것을 가져갔어. 자식들과 아내들까지! 남은 건 막내 아들 아하시야뿐이었지."},
  {"badge":"19","mr":"19",
   "en":"After these things, God put him on the path to a painful death by colon disease. And then he died, in great pain, unmourned. They buried him in the City of David, but not in the royal cemetery.",
   "ko":"이런 일들 후 하나님이 그를 대장병으로 고통스러운 죽음의 길로 두셨어. 그리고 그는 큰 고통 중에 죽었지. 아무도 애도하지 않았어. 다윗 성에 묻혔지만 왕실 묘지는 아니었지."},
  {"badge":"20","mr":"20",
   "en":"He was thirty-two years old when he became king and ruled in Jerusalem for eight years. Nobody was sorry to see him go \u2014 not a single tear was shed. They buried him in the City of David, but not in the royal cemetery.",
   "ko":"왕이 될 때 32살이었고 예루살렘에서 8년 동안 다스렸어. 그가 떠나는 걸 아쉬워한 사람은 아무도 없었어. 눈물 한 방울도 흘리지 않았지. 다윗 성에 묻혔지만 왕실 묘지는 아니었어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 21장 7문단 1:1 매핑)"],
},
22: {
 "title_en": "Ahaziah and Athaliah",
 "title_ko": "아하시야와 아달랴",
 "units": [
  {"badge":"1-6","mr":"1-6",
   "en":"The people of Jerusalem made Ahaziah, the youngest of Jehoram's sons, king in his place \u2014 the raiders who came with the Arabs against the camp had killed all the older sons. That's why Ahaziah, son of Jehoram, became king of Judah. Ahaziah was twenty-two years old when he became king, and he ruled in Jerusalem for one year. His mother was Athaliah, the granddaughter of Omri. He lived badly, just like the Ahab family. His mother gave him, as usual, bad advice. He did evil in the eyes of God, just like the Ahab family. They were his counselors after the death of his father \u2014 they were the reason he was such a disaster. But then, at their counsel, he joined Joram, son of Ahab, king of Israel, in war against Hazael, king of Aram, at Ramoth Gilead. Joram was wounded by the Arameans, and he went to Jezreel to recover from the wounds he got in Ramah in the war against Hazael, king of Aram. Ahaziah, son of Jehoram and king of Judah, went down to visit Joram, son of Ahab, in Jezreel to see how he was doing.",
   "ko":"예루살렘 사람들이 여호람의 막내 아들 아하시야를 왕으로 세웠어. 아라비아 사람들과 함께 진영을 치러 온 약탈자들이 나이 많은 아들들을 모두 죽였거든. 그래서 여호람의 아들 아하시야가 유다 왕이 됐지. 아하시야는 왕이 될 때 22살이었고 예루살렘에서 1년 동안 다스렸어. 어머니는 오므리의 손녀 아달랴였지. 아합 집안처럼 나쁘게 살았어. 어머니가 평소대로 나쁜 조언을 해줬거든. 아합 집안처럼 하나님 눈에 악을 행했어. 아버지가 죽은 후 그들이 그의 조언자가 됐지. 그가 재앙이 된 이유야. 그러다 그들의 조언대로 아합의 아들 이스라엘 왕 요람과 함께 길르앗 라못에서 아람 왕 하사엘과 전쟁했어. 요람이 아람 사람들에게 부상당했고, 라맛에서 아람 왕 하사엘과의 전쟁에서 입은 상처를 치료하려고 이스르엘로 내려갔지. 여호람의 아들 유다 왕 아하시야가 이스르엘로 내려가 아합의 아들 요람을 문병했어."},
  {"badge":"7-9","mr":"7-9",
   "en":"The visit of Ahaziah to Joram turned out to be a fatal mistake \u2014 God was behind it. He met Jehu son of Nimshi, whom God had chosen to finish off the Ahab family. Jehu met up with some relatives of Ahaziah, the king of Judah. \u201cWho are you?\u201d he asked. \u201cNephews of Ahaziah,\u201d they said. \u201cWe've come to visit the king's sons and the queen's sons.\u201d They were captured and then killed in the cistern at Beth Eked \u2014 forty-two of them. He didn't leave one alive. Ahaziah went into hiding in Samaria. But they found him and brought him to Jehu. They killed him and then buried him. They said, \u201cAfter all, he is the grandson of Jehoshaphat, who gave his whole life to seeking God.\u201d But there was no one in Ahaziah's family strong enough to rule the kingdom.",
   "ko":"아하시야의 요람 방문은 치명적 실수가 됐어. 하나님이 그 뒤에 계셨거든. 님시의 아들 예후를 만났지. 하나님이 아합 집안을 끝내려고 선택하신 사람. 예후가 유다 왕 아하시야의 친척 몇 명을 만났어. \u201c너희는 누구냐?\u201d 물었지. \u201c아하시야의 조카들입니다,\u201d 그들이 말했어. \u201c왕자들과 왕후의 아들들을 문병하러 왔습니다.\u201d 붙잡혀 벧에겟 우물에서 죽임을 당했어. 42명이었지. 한 명도 살려두지 않았어. 아하시야는 사마리아에 숨었어. 하지만 찾아내 예후에게 끌고 왔지. 죽이고 묻었어. 사람들이 말했지. \u201c어쨌든 그는 여호사밧의 손자야. 평생 하나님을 찾는 데 바친 사람이야.\u201d 하지만 아하시야 가문에는 나라를 다스릴 만한 강한 자가 없었어."},
  {"badge":"10","mr":"10",
   "en":"When Athaliah, mother of Ahaziah, learned that her son was dead, she took over. She began by massacring all the potential heirs to the throne in the family of Judah.",
   "ko":"아하시야의 어머니 아달랴가 아들이 죽은 걸 알자 정권을 잡았어. 먼저 유다 왕가의 왕위 계승 후보들을 모두 학살하는 것부터 시작했지."},
  {"badge":"11-12","mr":"11-12",
   "en":"But Jehosheba, the king's daughter, grabbed Joash, the son of Ahaziah, and, taking him from among the king's sons who were being killed, hid him and his nurse in a bedroom. Jehosheba, daughter of King Jehoram and wife of Jehoiada the priest \u2014 she was Ahaziah's sister \u2014 kept him hidden from Athaliah so she couldn't kill him. He was there with her, hidden in The Temple of God, for six years. Athaliah, meanwhile, was in charge of the country.",
   "ko":"하지만 왕의 딸 여호세바가 아하시야의 아들 요아스를 낚아챘어. 죽임을 당하던 왕자들 사이에서 그를 데리고 와 유모와 함께 침실에 숨겼지. 여호람 왕의 딸이자 제사장 여호야다의 아내 \u2014 아하시야의 누이 \u2014 인 여호세바가 아달랴에게서 그를 숨겨 죽이지 못하게 했어. 그는 6년 동안 하나님의 성전에 그녀와 함께 숨겨져 있었지. 그동안 아달랴가 나라를 다스렸어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 22장 4문단 1:1 매핑; 기존 수집본 22:1-6 중복 아티팩트 확인됨 — 새 원문 도착 시 정리)"],
},
23: {
 "title_en": "Joash Crowned King",
 "title_ko": "요아스가 왕위에 오르다",
 "units": [
  {"badge":"1-3","mr":"1-3",
   "en":"In the seventh year, Jehoiada finally got up the courage to do something \u2014 and he didn't do it alone. He got a group of men together to back him: Azariah son of Jeroham, Ishmael son of Jehohanan, Azariah son of Obed, Maaseiah son of Adaiah, and Elishaphat son of Zicri. They traveled throughout Judah and gathered the Levites from all the cities of Judah, plus the family heads from Israel, and all came to Jerusalem. They all gathered in The Temple of God, and made a covenant with the king.",
   "ko":"7년째 되는 해에 여호야다가 마침내 용기를 내어 행동에 나섰어. 혼자 한 게 아니야. 함께할 사람들을 모았지. 여로함의 아들 아사랴, 여호하난의 아들 이스마엘, 오벳의 아들 아사랴, 아다야의 아들 마아세야, 시그리의 아들 엘리사밧. 유다 전역을 돌며 유다 모든 성읍에서 레위인들과 이스라엘의 족장들을 모아 예루살렘으로 왔어. 모두 하나님의 성전에 모여 왕과 언약을 맺었지."},
  {"badge":"4-7","mr":"4-7",
   "en":"Jehoiada said, \u201cThe king's son will be king, just as God promised regarding David's children. Now pay attention! This is how you will do it: A third of you priests and Levites who come on duty on the Sabbath will guard the doors; another third will guard the palace; and the other third will guard the Foundation Gate. All the people will be in the courtyards of The Temple of God. No one may enter The Temple of God except the priests and designated Levites \u2014 they are permitted because they are consecrated; everyone else must observe God's rules and stay out. The Levites will form a ring around the king \u2014 fully armed \u2014 and any intruder will be killed. Stay close to the king, and don't lose sight of him.\u201d",
   "ko":"여호야다가 말했어. \u201c왕의 아들이 왕이 될 거야. 하나님이 다윗의 자손에게 약속하신 대로. 이제 잘 들어! 이렇게 할 거야. 안식일에 근무에 들어가는 제사장과 레위인 중 3분의 1은 문을 지키고, 3분의 1은 왕궁을 지키고, 나머지 3분의 1은 기초 문을 지켜. 모든 백성은 하나님의 성전 뜰에 있을 거야. 제사장과 지정된 레위인 외에는 하나님의 성전에 들어갈 수 없어. 그들은 거룩하게 구별됐으니까 허락되는 거야. 나머지는 하나님의 규칙을 지키고 밖에 있어야 해. 레위인들은 왕을 둘러싸고 고리를 만들어 \u2014 완전무장하고 \u2014 침입자는 죽여. 왕 곁에 바짝 붙어 있고, 눈을 떼지 마.\u201d"},
  {"badge":"8-10","mr":"8-10",
   "en":"The Levites and all Judah did exactly what Jehoiada the priest ordered. Each took his men \u2014 those coming on duty on the Sabbath and those going off duty \u2014 for Jehoiada the priest hadn't exempted any of the divisions. Jehoiada the priest gave the captains the spears and the large and small shields that had once belonged to King David and were now stored in The Temple of God. He stationed all the people, each with his weapon in his hand, in a ring from the south side of the Temple to the north side, covering the Altar and the Temple.",
   "ko":"레위인과 온 유다가 제사장 여호야다의 명령대로 정확히 했어. 각자 자기 부하를 데리고 \u2014 안식일에 근무 들어가는 자들과 나가는 자들 \u2014 여호야다 제사장이 어떤 부대도 면제하지 않았거든. 여호야다 제사장이 지휘관들에게 다윗 왕의 것이었다가 지금 하나님의 성전에 보관된 창과 대소 방패를 나눠줬어. 모든 백성을 각자 손에 무기를 들고 성전 남쪽부터 북쪽까지 고리를 이루게 배치했지. 제단과 성전을 에워싸게."},
  {"badge":"11","mr":"11",
   "en":"Then they brought out the king's son and put a crown on him, handed him the scroll of God's covenant, and made him king. Jehoiada and his sons anointed him, and everyone shouted, \u201cLong live the king!\u201d",
   "ko":"그러자 왕의 아들을 데리고 나와 왕관을 씌우고, 하나님의 언약 두루마리를 주고, 왕으로 세웠어. 여호야다와 그 아들들이 기름을 부었고, 모두가 외쳤지. \u201c왕 만세!\u201d"},
  {"badge":"12-15","mr":"12-15",
   "en":"Athaliah heard the noise from the crowd of runners and the people; she came to the people at The Temple of God. Looking, she saw the king standing by the pillar at the entrance. The captains and the trumpeters were by the king's side, and everyone was rejoicing and blowing trumpets, with singers and instruments leading the celebration. Athaliah tore her clothes in a rage and said, \u201cTreason! Treason!\u201d The priest Jehoiada gave orders to the captains who were in charge of the army: \u201cTake her out between the ranks and kill anyone who tries to follow her.\u201d The priest told them to make sure that Athaliah was not killed in The Temple of God. They arrested her and took her to the entrance of the Horse Gate at the royal palace and killed her there.",
   "ko":"아달랴가 달리는 무리와 백성의 소란을 듣고 하나님의 성전에 있는 백성에게 왔어. 보니 왕이 입구 기둥 곁에 서 있었지. 지휘관들과 나팔수들이 왕 곁에 있었고, 모두가 기뻐하며 나팔을 불었어. 노래하는 이들과 악기들이 축하를 이끌었지. 아달랴가 분노하며 옷을 찢고 말했어. \u201c반역이다! 반역이다!\u201d 제사장 여호야다가 군대를 맡은 지휘관들에게 명령했어. \u201c그녀를 대열 사이로 끌어내라. 따라오려는 자는 누구든 죽여라.\u201d 제사장은 아달랴가 하나님의 성전에서 죽지 않도록 하라고 지시했지. 그녀를 체포해 왕궁의 말 문 입구로 끌고 가 거기서 죽였어."},
  {"badge":"16-17","mr":"16-17",
   "en":"Then Jehoiada made a covenant between himself, all the people, and the king \u2014 that they would be God's people. The people poured into the temple of Baal and tore it down, smashing altar and images to smithereens. They killed Mattan the priest of Baal in front of the altar.",
   "ko":"그러자 여호야다가 자기와 온 백성과 왕 사이에 언약을 맺었어. 하나님의 백성이 되기로. 백성이 바알 신전으로 몰려가 헐어버렸어. 제단과 우상들을 산산조각 내고. 바알의 제사장 맛단을 제단 앞에서 죽였지."},
  {"badge":"18-21","mr":"18-21",
   "en":"Jehoiada put the supervision of The Temple of God into the hands of the Levitical priests, the ones designated by David for the work of The Temple of God \u2014 to offer Whole-Burnt-Offerings to God as set out in The Revelation of Moses, and to praise in song \u2014 as David had instructed. He also put guards at the gates of The Temple of God so that no one who was unclean in any way could enter. Then he got everyone involved \u2014 the officers, the nobles, the rulers of the people, and the people themselves \u2014 and escorted the king down from The Temple of God, through the Upper Gate, and placed him on the throne. That's when everyone celebrated \u2014 the city was quiet. Athaliah was dead \u2014 killed by the sword.",
   "ko":"여호야다가 하나님의 성전 감독을 레위 제사장들 손에 맡겼어. 다윗이 하나님의 성전 일을 위해 지정한 이들 \u2014 모세의 계시에 기록된 대로 하나님께 번제를 드리고 노래로 찬양하도록 \u2014 다윗이 지시한 대로. 하나님의 성전 문들에 파수꾼도 세워 어떤 식으로든 부정한 자는 들어오지 못하게 했지. 그리고 모두를 참여시켰어. 장교들, 귀족들, 백성의 지도자들, 백성 자신들. 왕을 하나님의 성전에서 호위하여 위 문을 통해 내려가 왕좌에 앉혔어. 그때 모두가 축하했지. 도시는 조용했어. 아달랴는 죽었어. 칼에 죽임을 당했지."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 23장 7문단 1:1 매핑)"],
},
24: {
 "title_en": "Joash: Good Start, Bad End",
 "title_ko": "요아스: 좋은 시작, 나쁜 끝",
 "units": [
  {"badge":"1-3","mr":"1-3",
   "en":"Joash was seven years old when he became king; he ruled for forty years in Jerusalem. His mother was Gazelle (Zibiah), from Beersheba. Taught and trained by Jehoiada the priest, Joash did what pleased God throughout Jehoiada's lifetime. Jehoiada picked out two wives for him \u2014 he had a family of sons and daughters.",
   "ko":"요아스는 왕이 될 때 7살이었고 예루살렘에서 40년 동안 다스렸어. 어머니는 브엘세바 출신 가젤(시브야)였지. 여호야다 제사장에게 가르침과 훈련을 받은 요아스는 여호야다가 살아 있는 동안 하나님을 기쁘시게 하는 일을 했어. 여호야다가 두 아내를 골라줬지. 아들딸 많은 가정을 이뤘어."},
  {"badge":"4-7","mr":"4-7",
   "en":"The time came when Joash decided to renovate The Temple of God. He got the priests and Levites together and said, \u201cGo out through the towns of Judah and collect the money due as temple taxes from the people for the annual maintenance of The Temple of God. Do it promptly.\u201d But the Levites didn't do it promptly. The king called for Jehoiada, the chief priest, and said, \u201cWhy haven't you made the Levites bring in from Judah and Jerusalem the tax imposed by Moses, servant of God, and the congregation of Israel, for the Tent of Covenant?\u201d (wicked Queen Athaliah and her sons had broken into The Temple of God and stolen everything in it for use in Baal worship.)",
   "ko":"때가 되어 요아스가 하나님의 성전을 보수하기로 했어. 제사장들과 레위인들을 모아 말했지. \u201c유다 성읍들로 나가 하나님의 성전 연간 유지비로 백성에게서 거둘 성전세를 거둬와. 신속히 해.\u201d 하지만 레위인들은 신속히 하지 않았어. 왕이 대제사장 여호야다를 불러 말했어. \u201c왜 레위인들에게 유다와 예루살렘에서 하나님의 종 모세와 이스라엘 회중이 언약의 장막을 위해 부과한 세를 가져오게 하지 않았소?\u201d (사악한 아달랴 여왕과 그 아들들이 하나님의 성전을 침입해 안의 모든 것을 훔쳐 바알 숭배에 썼거든.)"},
  {"badge":"8-11","mr":"8-11",
   "en":"The king ordered a chest to be made, and it was placed outside, at the entrance to The Temple of God. Then they made a proclamation in Judah and Jerusalem: Bring to God the tax that Moses, servant of God, had imposed on Israel in the wilderness. People were delighted to do it, and they brought it. They dropped money in the chest until it was full. Every time the chest was full, the Levites would bring it to the king's officials. Then the king's secretary and the chief priest's appointee would empty the chest and return it to its place. They did this every day until they had a large amount of money.",
   "ko":"왕이 궤를 만들라 명령했고, 하나님의 성전 입구 밖에 두었어. 그리고 유다와 예루살렘에 선포했지. 하나님의 종 모세가 광야에서 이스라엘에 부과한 세를 하나님께 가져오라고. 백성은 기쁘게 했어. 가져왔지. 궤가 찰 때까지 돈을 넣었어. 궤가 찰 때마다 레위인들이 왕의 관리들에게 가져왔지. 그러면 왕의 서기관과 대제사장의 대리인이 궤를 비우고 제자리에 돌려놨어. 큰돈이 모일 때까지 매일 이렇게 했지."},
  {"badge":"12-14","mr":"12-14",
   "en":"The king and Jehoiada turned the money over to the construction foremen of The Temple of God. Then the foremen hired masons and carpenters to restore The Temple of God. They also hired blacksmiths and workers in bronze to repair The Temple of God. The workers kept at it until they had finished the repair \u2014 they restored The Temple of God to its original condition and reinforced it. They returned the rest of the money to the king and Jehoiada, who used it to make furnishings for The Temple of God \u2014 vessels for worship services, for Whole-Burnt-Offerings, and for the incense, along with dishes and other things made of gold and silver. During Jehoiada's lifetime, they continued to offer Whole-Burnt-Offerings at The Temple of God.",
   "ko":"왕과 여호야다가 그 돈을 하나님의 성전 공사 감독들에게 넘겼어. 감독들이 석수와 목수를 고용해 하나님의 성전을 복원했지. 대장장이와 놋쇠 일꾼도 고용해 하나님의 성전을 수리했어. 일꾼들은 수리를 마칠 때까지 계속 일했지. 하나님의 성전을 원래 상태로 복원하고 보강했어. 남은 돈을 왕과 여호야다에게 돌려줬고, 그들은 하나님의 성전 기구를 만드는 데 썼지. 예배용 기구, 번제용 기구, 분향용 기구, 금과 은으로 만든 그릇과 다른 것들. 여호야다가 살아 있는 동안 하나님의 성전에서 번제를 계속 드렸어."},
  {"badge":"15-16","mr":"15-16",
   "en":"Jehoiada lived to a ripe old age. He died at 130. They buried him in the City of David with the kings because of all the good he had done for Israel \u2014 for God and The Temple.",
   "ko":"여호야다는 천수를 누리고 살았어. 130살에 죽었지. 다윗 성에 왕들과 함께 묻혔어. 이스라엘을 위해 \u2014 하나님과 성전을 위해 \u2014 한 모든 선한 일 때문이었지."},
  {"badge":"17-19","mr":"17-19",
   "en":"But after the death of Jehoiada, the leaders of Judah came and bowed down before the king, and the king listened to them. Then they deserted The Temple of God, the God of their ancestors, and worshiped the Asherah groves and idols. And God was angry with Judah and Jerusalem because of their guilt. God sent prophets to call them back to him, and they all preached, but no one paid any attention to them.",
   "ko":"하지만 여호야다가 죽은 후 유다 지도자들이 와서 왕 앞에 절하자 왕이 그들의 말을 들었어. 그러자 그들이 조상들의 하나님, 하나님의 성전을 버리고 아세라 목상과 우상들을 섬겼지. 하나님이 그들의 죄 때문에 유다와 예루살렘에 진노하셨어. 하나님이 선지자들을 보내 돌아오라 부르셨고, 모두 외쳤지만 아무도 귀 기울이지 않았어."},
  {"badge":"20-22","mr":"20-22",
   "en":"Then the Spirit of God moved Zechariah son of Jehoiada the priest to speak up: \u201cGod's word: Why do you cross God's command? You're going down a dead-end road. You've abandoned God, so he's abandoned you!\u201d But they conspired against him \u2014 and at the king's command, they stoned him to death in the courtyard of The Temple of God. That was the thanks King Joash showed the loyal Jehoiada, the priest who had protected and saved his life. He decided to kill his son. As he was dying, Zechariah called out, \u201cLook at this, God! You take care of this!\u201d",
   "ko":"그때 하나님의 영이 제사장 여호야다의 아들 스가랴를 감동시켜 외치게 하셨어. \u201c하나님의 말씀이다. 왜 하나님의 명령을 어기느냐? 막다른 길로 가고 있다. 너희가 하나님을 버렸으니 그도 너희를 버리셨다!\u201d 하지만 그들이 공모했어. 왕의 명령으로 하나님의 성전 뜰에서 돌로 쳐 죽였지. 요아스 왕이 충성스러운 여호야다 \u2014 자기 생명을 보호하고 구해준 제사장 \u2014 에게 보인 감사가 그거였어. 그 아들을 죽이기로 한 거야. 죽어가며 스가랴가 외쳤어. \u201c하나님, 보십시오! 이걸 처리해주십시오!\u201d"},
  {"badge":"23-24","mr":"23-24",
   "en":"That spring, the Aramean army invaded Judah. They reached Jerusalem and massacred the leaders of the people and sent all the plunder they collected to the king of Damascus. The Aramean army came with a small force, but God gave them a large army as plunder because Judah had abandoned the God of their ancestors. So Joash got what he deserved.",
   "ko":"그 봄에 아람 군대가 유다를 침공했어. 예루살렘에 이르러 백성의 지도자들을 학살하고 모은 전리품을 다마스쿠스 왕에게 보냈지. 아람 군대는 작은 병력으로 왔지만, 유다가 조상들의 하나님을 버렸기 때문에 하나님이 큰 군대를 노획물로 주셨어. 요아스는 받을 걸 받은 거야."},
  {"badge":"25","mr":"25",
   "en":"They left Joash badly wounded. Then his servants plotted against him for murdering the son of Jehoiada the priest. They killed him in his bed. They buried him in the City of David, but not in the royal cemetery.",
   "ko":"그들이 요아스를 크게 부상당한 채로 두고 갔어. 그러자 신하들이 제사장 여호야다의 아들을 죽인 일로 공모했지. 침대에서 죽였어. 다윗 성에 묻었지만 왕실 묘지는 아니었어."},
  {"badge":"26-27","mr":"26-27",
   "en":"The two conspirators were Zabad son of Shimeath the Ammonite woman and Jehozabad son of Shimrith the Moabite woman. The story of his sons, the many prophecies about him, and the account of his restoration of The Temple of God can be found in the The Commentary on the Book of the Kings. Amaziah, his son, became the next king.",
   "ko":"두 공모자는 암몬 여인 시므앗의 아들 사밧과 모압 여인 시므릿의 아들 여호사밧이었어. 그의 아들들 이야기, 그에 대한 많은 예언들, 하나님의 성전 복원 기록은 열왕기 주석서에 나와 있어. 아들 아마샤가 다음 왕이 됐지."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 24장 10문단 1:1 매핑)"],
},
25: {
 "title_en": "Amaziah's Pride and Fall",
 "title_ko": "아마샤의 교만과 몰락",
 "units": [
  {"badge":"1-4","mr":"1-4",
   "en":"Amaziah was twenty-five years old when he became king and ruled in Jerusalem for twenty-nine years. His mother was Jehoaddin from Jerusalem. He lived well, but not wholeheartedly. He was, in short, a little wishy-washy in doing God's will. When he had the kingdom firmly in hand, he executed the servants who had killed his father the king. But he didn't kill their children \u2014 he obeyed The Revelation in The Book of Moses, God saying, \u201cDon't kill parents for the sins of the children, don't kill children for the sins of the parents; each person will get his comeuppance.\u201d",
   "ko":"아마샤는 왕이 될 때 25살이었고 예루살렘에서 29년 동안 다스렸어. 어머니는 예루살렘 출신 여호앗딘이였지. 잘 살았지만 전심으로는 아니었어. 한마디로 하나님의 뜻을 행하는 데 조금 우유부단했지. 나라를 확고히 잡자 아버지 왕을 죽인 신하들을 처형했어. 하지만 그들의 자식들은 죽이지 않았어. 모세의 책에 있는 계시를 따랐거든. 하나님께서 \u201c자식의 죄로 부모를 죽이지 말고, 부모의 죄로 자식을 죽이지 마라. 각 사람은 자기 죗값을 받을 거다\u201d라고 하셨지."},
  {"badge":"5-8","mr":"5-8",
   "en":"Amaziah organized Judah and sorted out Judah and Benjamin by families, under captains of thousands and of hundreds. He took a census: all males twenty years and older, and got a count of 300,000 able-bodied men who could handle a spear and shield. He also hired 100,000 soldiers from Israel at a cost of about four tons of silver. A holy man showed up and said, \u201cNo, O king \u2014 don't let the Israelite army into this, because God is not on their side \u2014 not with any of the Ephraimites \u2014 and will make you fall flat on your face \u2014 God doesn't take sides, and he'll put you on the losing side if you go ahead with this!\u201d Amaziah said to the holy man, \u201cBut what about all this money \u2014 these tons of silver I have already paid out?\u201d The holy man said, \u201cGod's help is worth far more to you than that!\u201d So Amaziah dismissed the hired soldiers and sent them home. They were furious, and went home in a rage.",
   "ko":"아마샤가 유다를 조직하고 유다와 베냐민을 가문별로 천부장과 백부장 아래 정리했어. 인구 조사를 했지. 20살 이상 남자 전부, 창과 방패를 다룰 수 있는 건장한 남자 30만 명을 셌어. 또 이스라엘에서 은 4톤 정도를 주고 병사 10만 명을 고용했지. 한 성자가 나타나 말했어. \u201c안 됩니다, 왕이시여. 이스라엘 군대를 이 일에 끌어들이지 마십시오. 하나님이 그들 편이 아니시고 \u2014 에브라임 사람 그 누구와도 함께하지 않으시니 \u2014 얼굴을 땅에 박게 하실 겁니다. 하나님은 편들지 않으시지만, 강행하면 지는 편에 서게 하실 겁니다!\u201d 아마샤가 성자에게 말했어. \u201c하지만 이 돈은 어떡하죠. 이미 지불한 은 몇 톤이요?\u201d 성자가 말했어. \u201c하나님의 도움은 그거보다 훨씬 값집니다!\u201d 그래서 아마샤가 고용병들을 해산시키고 집으로 보냈어. 그들은 격분했고, 분노하며 집으로 갔지."},
  {"badge":"9-10","mr":"9-10",
   "en":"But Amaziah was optimistic. He marched his army to the Valley of Salt and killed 10,000 men of Seir. The Judahites took another 10,000 alive and marched them to the top of the Rock and threw them down; they were all dashed to pieces.",
   "ko":"하지만 아마샤는 낙관적이었어. 군대를 이끌고 소금 골짜기로 가서 세일 사람 1만 명을 죽였지. 유다 사람들이 또 1만 명을 산 채로 잡아 셀라 바위 꼭대기로 끌고 가서 던져버렸어. 모두 산산조각 났지."},
  {"badge":"11-12","mr":"11-12",
   "en":"But the hired soldiers that Amaziah had sent home \u2014 the ones who had been told they were not allowed to go to war with him \u2014 went on a rampage, raiding the towns of Judah from Samaria to Beth Horon, killing 3,000 people and carrying off a great deal of loot.",
   "ko":"하지만 아마샤가 집으로 돌려보낸 고용병들 \u2014 그와 함께 전쟁에 나갈 수 없다고 통보받은 자들 \u2014 이 날뛰며 사마리아부터 벧호론까지 유다 성읍들을 약탈했어. 3,000명을 죽이고 엄청난 전리품을 가져갔지."},
  {"badge":"13","mr":"13",
   "en":"On his return from the defeat of the Edomites, Amaziah brought back the gods of the Seirites and installed them as his own gods, worshiping them and burning incense to them.",
   "ko":"에돔 사람들을 무찌르고 돌아오면서 아마샤가 세일 사람들의 신들을 가져와 자기 신으로 세우고, 그들을 섬기며 분향했어."},
  {"badge":"14-16","mr":"14-16",
   "en":"That ignited God's anger. God sent a prophet who said, \u201cWhy on earth are you praying to these gods who couldn't even save their own people from you?\u201d The prophet was still speaking when Amaziah interrupted: \u201cDid I ask for your advice? Shut up \u2014 before I have you killed!\u201d The prophet, still speaking, said, \u201cNo more advice \u2014 I can see that God has decided to destroy you, because you have done all this and haven't listened to a word I said.\u201d",
   "ko":"그게 하나님의 분노를 일으켰어. 하나님이 선지자를 보내 말씀하셨지. \u201c도대체 왜 자기 백성도 너에게서 구하지 못한 신들에게 기도하느냐?\u201d 선지자가 말하고 있는데 아마샤가 끼어들었어. \u201c내가 네 조언을 구했나? 입 다물어. 죽이기 전에!\u201d 선지자가 말을 이으며 말했어. \u201c더 이상 조언 안 해. 하나님이 너를 멸하기로 작정하신 게 보여. 네가 이 모든 일을 하고 내 말을 한마디도 듣지 않았으니까.\u201d"},
  {"badge":"17-19","mr":"17-19",
   "en":"After thinking it over, Amaziah, king of Judah, sent a challenge to Jehoash, son of Jehoahaz, son of Jehu, king of Israel: \u201cCome and meet with me \u2014 face to face!\u201d Jehoash, king of Israel, replied to Amaziah, king of Judah: \u201cThe thornbush in Lebanon sent word to the cedar in Lebanon: 'Give your daughter to my son in marriage.' But a wild animal from Lebanon passed by and stepped on the thornbush, crushing it. Just because you've beaten Edom in battle, you're getting all big and high and mighty. Relax, stay home. Why court disaster? Why get yourself and Judah killed?\u201d",
   "ko":"곰곰이 생각한 후 유다 왕 아마샤가 여호아하스의 아들 예후의 손자 이스라엘 왕 여호아스에게 도전장을 보냈어. \u201c나와 만나자. 얼굴을 맞대고!\u201d 이스라엘 왕 여호아스가 유다 왕 아마샤에게 답했어. \u201c레바논의 가시나무가 레바논의 백향목에게 전했지. '네 딸을 내 아들과 결혼시켜라.' 그런데 레바논의 들짐승이 지나가다 가시나무를 밟아 짓눌렀어. 에돔을 전투에서 이겼다고 우쭐대며 거만해졌구나. 진정해, 집에 있어. 왜 재앙을 자초해? 너와 유다가 죽게 될 텐데?\u201d"},
  {"badge":"20-21","mr":"20-21",
   "en":"But Amaziah wouldn't listen. God had already decided to let Jehoash defeat him \u2014 his punishment for worshiping the gods of Edom. So Jehoash, king of Israel, came on. The two of them faced off at Beth Shemesh, in Judah. Judah was thoroughly beaten by Israel \u2014 all the soldiers straggled home in defeat.",
   "ko":"하지만 아마샤가 듣지 않았어. 하나님이 이미 여호아스가 그를 이기게 하기로 작정하셨거든. 에돔의 신들을 섬긴 벌이었지. 그래서 이스라엘 왕 여호아스가 왔어. 둘이 유다의 벧세메스에서 맞붙었지. 유다가 이스라엘에게 철저히 깨졌어. 모든 병사가 패배한 채 집으로 흩어졌지."},
  {"badge":"22-24","mr":"22-24",
   "en":"Jehoash, king of Israel, captured Amaziah, king of Judah, the son of Joash, the son of Ahaziah, at Beth Shemesh. Then he entered Jerusalem, and tore down the Jerusalem wall from the Ephraim Gate to the Corner Gate \u2014 about 600 feet of wall. He looted the gold, silver, and furnishings, everything he found in The Temple of God that had been looked after by Obed-Edom, plus the palace treasuries. Then he took hostages and returned to Samaria.",
   "ko":"이스라엘 왕 여호아스가 유다 왕 아마샤 \u2014 요아스의 아들, 아하시야의 손자 \u2014 를 벧세메스에서 사로잡았어. 그리고 예루살렘에 들어가 에브라임 문부터 모퉁이 문까지 예루살렘 성벽을 허물었지. 약 600피트(약 180미터) 성벽. 금과 은과 기구들, 오벧에돔이 관리하던 하나님의 성전에서 찾은 모든 것과 왕궁 보물을 약탈했어. 그리고 인질을 잡아 사마리아로 돌아갔지."},
  {"badge":"25-28","mr":"25-28",
   "en":"Amaziah son of Joash, king of Judah, continued as king for fifteen years after the death of Jehoash son of Jehoahaz, king of Israel. The rest of the life and times of Amaziah from start to finish is written in the Royal Annals of the Kings of Israel and Judah. From the time Amaziah stopped following God, there was a conspiracy to get rid of him in Jerusalem. He ran away to Lachish, but they tracked him down in Lachish and killed him. They brought his body back on a horse and buried him in the City of David with his ancestors.",
   "ko":"유다 왕 요아스의 아들 아마샤는 이스라엘 왕 여호아하스의 아들 여호아스가 죽은 후 15년 동안 계속 왕이었어. 아마샤의 나머지 생애와 치세는 처음부터 끝까지 이스라엘과 유다 왕들의 왕실 연대기에 기록되어 있어. 아마샤가 하나님 따르기를 그만둔 때부터 예루살렘에서 그를 제거하려는 음모가 있었어. 라기스로 도망쳤지만 라기스에서 추적당해 죽임을 당했지. 시신을 말에 실어 가져와 다윗 성에 조상들과 함께 묻었어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 25장 11문단 1:1 매핑)"],
},
}
