# -*- coding: utf-8 -*-
"""2Chronicles ch13-16 teen EN/KO (작업자 D2, MSG 직역 기반 초벌)."""
CHAPTERS = {
13: {
 "title_en": "Abijah's Bold Speech Before the Battle",
 "title_ko": "전투 전 아비야의 담대한 연설",
 "units": [
  {"badge":"1-2","mr":"1-2","header_en":"King Abijah","header_ko":"아비야 왕",
   "en":"Here's how it all started: in the eighteenth year of King Jeroboam's rule, Abijah took over the throne of Judah. He ruled from Jerusalem for three years. His mother was Maacah, the daughter of Uriel from Gibeah.",
   "ko":"자, 얘기 시작해볼게. 여로보암 왕이 다스린 지 18년째 되던 해에 아비야가 유다 왕위를 이었어. 예루살렘에서 3년 동안 다스렸지. 엄마는 기브아 출신 우리엘의 딸 마아가였어."},
  {"badge":"3","mr":"2-3",
   "en":"Then war broke out between Abijah and Jeroboam. Abijah marched out with 400,000 of his best soldiers \u2014 and Jeroboam showed up with 800,000 of his best. Abijah was outnumbered two to one.",
   "ko":"그러다 아비야와 여로보암 사이에 전쟁이 터졌어. 아비야는 정예병 40만 명을 이끌고 나갔는데, 여로보암은 정예병 80만 명을 끌고 나왔어. 아비야 쪽이 딱 절반이었지."},
  {"badge":"4-7","mr":"4-7",
   "en":"Abijah climbed to a high point on Mount Zemaraim in the hill country of Ephraim and gave this speech: \u201cListen up, Jeroboam and all Israel! Don't you realize that God \u2014 the one and only God of Israel \u2014 made David and his sons the permanent rulers of Israel? It was sealed with a 'covenant of salt' \u2014 God's kingdom, ruled by God's king. But then what happened? Jeroboam \u2014 the son of Nebat, who was just one of Solomon's servants \u2014 rebelled against his master. All the troublemakers joined his cause, and they were too much for Rehoboam, Solomon's true heir. Rehoboam had no clue what he was doing \u2014 honestly, he was a coward who couldn't stand up to them.\u201d",
   "ko":"아비야가 에브라임 산지 스마라임 산 꼭대기 눈에 잘 띄는 곳에 올라가서 이렇게 연설했어. \u201c들어봐, 여로보암과 온 이스라엘아! 아직도 모르겠어? 하나님 \u2014 이스라엘의 유일하신 하나님 \u2014 이 다윗과 그 자손들을 이스라엘의 영원한 왕으로 세우셨어. '소금 언약'으로 굳게 하신 거야 \u2014 하나님의 나라를 하나님의 왕이 다스리는 거지. 그런데 어떻게 됐어? 여로보암 \u2014 솔로몬의 종 느밧의 아들에 불과한 자가 \u2014 자기 주인을 배반했잖아. 온갖 불량배들이 그에게 붙어서 솔로몬의 정통 후계자 르호보암을 압도해버렸지. 르호보암은 어찌할 바를 몰랐어 \u2014 솔직히 말하면 겁쟁이라서 그들에게 맞서지도 못했어.\u201d"},
  {"badge":"8-9","mr":"8-9",
   "en":"\u201cAnd now you're taking advantage of that weakness, pushing back against God's rule through David's family \u2014 you think you're so tough with your huge army and those golden-calf idols Jeroboam made for you to worship as gods! But look at what you've done: you threw out God's priests \u2014 the sons of Aaron \u2014 and the Levites, and just appointed priests however you pleased, like the pagan nations do. Anyone who shows up with enough money to pay for it can become a priest! A priest of No-God!\u201d",
   "ko":"\u201c그리고 너희는 그 약점을 틈타 다윗 자손을 통한 하나님의 다스림에 맞서고 있어 \u2014 대군대와 여로보암이 너희 신으로 만들어준 금송아지 우상들을 믿고 그렇게 기세등등한 거지! 그런데 너희가 무슨 짓을 했는지 봐봐. 하나님의 제사장들 \u2014 아론의 자손들과 레위인들을 쫓아내고, 이방 나라들처럼 자기들 마음대로 제사장을 세웠잖아. 돈만 충분히 들고 오면 누구든 제사장이 될 수 있어! No-God의 제사장이라고!\u201d"},
  {"badge":"10-11","mr":"10-11",
   "en":"\u201cBut here in Judah, we're sticking with God. We haven't traded him in for some new model \u2014 we're keeping the tried-and-true: the priests of Aaron leading us to God, and the Levites leading us in worship \u2014 sacrificing Whole-Burnt-Offerings and fragrant incense to God at the morning and evening prayers, setting out fresh holy bread on a clean table, and lighting the lamps on the golden Lampstand every night. We keep doing exactly what God told us to do, exactly the way he told us to do it. You guys? You've gotten rid of him completely.\u201d",
   "ko":"\u201c하지만 우리 유다는 하나님과 함께 가. 최신형으로 갈아탄 게 아니야 \u2014 검증된 본래 방식을 지키는 거지. 아론의 자손 제사장들이 우리를 하나님께로 인도하고, 레위인들이 예배를 인도해. 아침저녁 기도 시간에 하나님께 번제와 향기로운 향을 드리고, 깨끗한 상에 신선한 거룩한 떡을 차려놓고, 매일 밤 금 등잔대의 등불을 켜. 하나님이 하라고 하신 것을 하나님이 하라고 하신 방식으로 계속 하는 거야. 너희는? 하나님을 완전히 버렸잖아.\u201d"},
  {"badge":"12","mr":"12",
   "en":"\u201cCan't you see what's obvious? God is on our side \u2014 he's our commander. His priests are standing by with trumpets, ready to sound the battle signal. So listen, Israel: don't fight against God, the God of your ancestors. You will not win this battle.\u201d",
   "ko":"\u201c뻔한 게 안 보여? 하나님이 우리 편이야 \u2014 하나님이 우리의 지휘관이셔. 하나님의 제사장들이 나팔을 들고 대기 중이야. 전투 신호를 불 준비가 다 됐다고. 그러니까 들어, 이스라엘아. 하나님, 너희 조상들의 하나님과 싸우지 마. 이 전투에서는 절대 못 이겨.\u201d"},
  {"badge":"13-18","mr":"13-18",
   "en":"Here's the wild part: while Abijah was still speaking, Jeroboam had secretly sent troops around to ambush them from behind \u2014 Jeroboam's army in front of Judah, the ambush behind them. When Judah looked back and realized they were trapped, attacked from front and back, they cried out to God in desperation. The priests blew their trumpets, and the soldiers of Judah raised their battle cry. And at that battle cry, God routed Jeroboam and all Israel right in front of Abijah and Judah. Israel's army scattered before Judah \u2014 God handed them the victory. Abijah and his troops slaughtered them: 500,000 of Israel's best fighters were killed that day. Israel's army fell flat on its face \u2014 a totally humiliating defeat. Judah won hands down, because they trusted God, the God of their ancestors.",
   "ko":"그런데 반전이 있었어. 아비야가 말하는 동안 여로보암이 몰래 군대를 돌려 뒤에서 기습하게 했거든. 앞에는 여로보암 군대, 뒤에는 매복군이었지. 유다 군대가 뒤를 돌아보고 앞뒤로 포위된 걸 깨닫자 하나님께 필사적으로 부르짖었어. 제사장들이 나팔을 불고, 유다 병사들이 함성을 질렀지. 그 함성과 함께 하나님이 아비야와 유다 앞에서 여로보암과 온 이스라엘을 무찌르셨어. 이스라엘 군대는 유다 앞에서 흩어졌어 \u2014 하나님이 승리를 안겨주신 거야. 아비야와 그 군대가 그들을 도륙했는데, 그날 이스라엘 정예병 50만 명이 죽었어. 이스라엘 군대는 완전히 박살 났지 \u2014 굴욕적인 패배였어. 유다는 가뿐히 이겼어. 조상들의 하나님을 신뢰했기 때문이야."},
  {"badge":"19-21","mr":"19-21",
   "en":"Abijah didn't stop there \u2014 he chased Jeroboam down and captured the towns of Bethel, Jeshanah, and Ephron, along with all their surrounding villages. Jeroboam never recovered from that defeat as long as Abijah lived. Later on, God struck Jeroboam down and he died. Meanwhile Abijah was thriving: he married fourteen wives and ended up with twenty-two sons and sixteen daughters.",
   "ko":"아비야는 거기서 멈추지 않았어. 여로보암을 추격해서 벧엘, 여사나, 에브론 성읍들과 주변 마을들을 모두 점령했지. 여로보암은 아비야가 살아 있는 동안 그 패배에서 절대 회복하지 못했어. 나중에 하나님이 그를 치셔서 죽었지. 반면 아비야는 번성했어. 아내를 열넷이나 맞이해서 아들 스물둘, 딸 열여섯을 두었어."},
  {"badge":"22","mr":"22",
   "en":"Everything else about Abijah \u2014 what he did and said \u2014 is written down in the commentary written by Iddo the prophet.",
   "ko":"아비야에 관한 나머지 모든 일 \u2014 그가 행하고 말한 것들 \u2014 은 선지자 잇도가 쓴 주석책에 기록되어 있어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 13장 9문단 1:1 매핑; '2-3' 인쇄 중복 절 정리로 배지 '3' 사용)"],
},
14: {
 "title_en": "Asa Cleans House and Trusts God",
 "title_ko": "아사, 집안을 청소하고 하나님을 신뢰하다",
 "units": [
  {"badge":"1","mr":"1","header_en":"King Asa","header_ko":"아사 왕",
   "en":"Abijah died and was buried with his ancestors in the City of David. His son Asa became the next king. For the first ten years of Asa's reign, the country was at peace.",
   "ko":"아비야가 죽어 조상들과 함께 다윗 성에 묻혔어. 아들 아사가 다음 왕이 됐지. 아사가 다스린 첫 10년 동안 나라는 평안했어."},
  {"badge":"2-6","mr":"2-6",
   "en":"Asa was a good king \u2014 he did what was right in God's eyes. He cleaned house: he got rid of the pagan altars and shrines, smashed the sacred stone pillars, and chopped down the Asherah groves. He told Judah to center their lives on God, the God of their ancestors \u2014 to do what the law said and follow the commandments. Because he got rid of all the pagan shrines and altars in Judah's cities, his kingdom was at peace. And because the land was quiet with no war, he was able to build up a strong defense system in Judah. God kept the peace.",
   "ko":"아사는 선한 왕이었어 \u2014 하나님 보시기에 옳은 일을 했지. 집안 청소를 제대로 했어. 이방 제단과 산당을 없애고, 신성한 돌기둥들을 부수고, 아세라 숲을 찍어냈어. 유다 백성에게 조상들의 하나님을 삶의 중심으로 삼으라고 했지. 율법이 말한 대로 행하고 계명을 지키라고. 유다 성읍들의 이방 산당과 제단을 다 없앴더니 나라에 평화가 왔어. 전쟁 없이 땅이 조용하니까 유다의 방어 체계를 탄탄히 세울 수 있었지. 하나님이 평화를 지켜주셨어."},
  {"badge":"7","mr":"7",
   "en":"Asa said to his people, \u201cWhile we have the chance and the land is quiet, let's build a solid defense system \u2014 fortifying our cities with walls, towers, gates, and bars. We have this peaceful land because we sought God; he has given us rest from all our troubles.\u201d So they built, and enjoyed prosperity.",
   "ko":"아사가 백성에게 말했어. \u201c지금 기회가 있고 땅이 조용한 동안 탄탄한 방어 체계를 세우자. 성벽과 망대와 성문과 빗장으로 성읍들을 요새화하는 거야. 우리가 이 평안한 땅을 가진 건 하나님을 찾았기 때문이야. 하나님이 모든 환난에서 안식을 주셨어.\u201d 그래서 그들은 성을 쌓고 번영을 누렸어."},
  {"badge":"8","mr":"8",
   "en":"Asa had an army of 300,000 Judeans armed with shields and spears, plus another 280,000 Benjaminites carrying shields and bows. Every one of them a courageous warrior.",
   "ko":"아사에게는 방패와 창으로 무장한 유다 군대 30만 명에, 방패와 활을 든 베냐민 군대 28만 명이 더 있었어. 모두 용맹한 전사들이었지."},
  {"badge":"9-11","mr":"9-11",
   "en":"Then Zerah the Ethiopian marched against Asa with an army of a million men plus three hundred chariots, and got as far as Mareshah. Asa met him there, lining up for battle in the Valley of Zephathah near Mareshah. Then Asa prayed to God: \u201cO God, you aren't impressed by big numbers or intimidated by a show of force once you decide to help. Help us, O God! We've come out to meet this huge army because we trust in you and in who you are. Don't let mere mortals stand against you!\u201d",
   "ko":"그때 구스 사람 세라가 100만 대군에 전차 300대를 이끌고 아사를 치러 와서 마레사까지 왔어. 아사가 거기서 맞섰지. 마레사 근처 스바다 골짜기에서 전투 대형을 갖췄어. 그리고 아사가 하나님께 기도했어. \u201c하나님, 일단 도우시기로 작정하시면 큰 숫자에도 마음이 움직이지 않으시고 무력시위에도 겁먹지 않으시죠. 우리를 도와주소서, 하나님! 우리가 이 대군을 맞서러 나온 건 당신을 신뢰하고 당신이 어떤 분인지 알기 때문입니다. 한낱 인간이 당신께 맞서지 못하게 하소서!\u201d"},
  {"badge":"12-15","mr":"12-15",
   "en":"God defeated the Ethiopians right in front of Asa and Judah \u2014 the Ethiopians ran for their lives. Asa and his men chased them all the way to Gerar. So many Ethiopians were killed that there was no fight left in them \u2014 a total wipeout, with God and his troops doing the crushing. Judah carted off loads of plunder. They devastated all the towns around Gerar, whose people were helpless, paralyzed by the fear of God, and looted the whole countryside. They even raided the herdsmen's camps and brought back loads of sheep and camels to Jerusalem.",
   "ko":"하나님이 아사와 유다 앞에서 구스 군대를 무찌르셨어 \u2014 구스 사람들은 목숨 걸고 도망쳤지. 아사와 그 군대가 그랄까지 추격했어. 구스 사람이 너무 많이 죽어서 싸울 기력조차 없었어 \u2014 하나님과 그 군대가 짓누른 완전한 섬멸이었지. 유다는 전리품을 잔뜩 챙겼어. 그랄 주변 성읍들도 초토화시켰는데, 그곳 사람들은 하나님의 두려움에 마비되어 속수무책이었거든. 온 시골을 약탈했지. 목자들의 진영까지 습격해서 양과 낙타를 잔뜩 끌고 예루살렘으로 돌아왔어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 14장 6문단 1:1 매핑)"],
},
15: {
 "title_en": "Asa's Big Cleanup and the Covenant",
 "title_ko": "아사의 대청소와 언약",
 "units": [
  {"badge":"1-6","mr":"1-6",
   "en":"Then Azariah son of Obed, moved by the Spirit of God, went out to meet Asa. He said, \u201cListen carefully, Asa \u2014 and listen, Judah and Benjamin: God will stick with you as long as you stick with him. If you look for him, he will let himself be found; but if you leave him, he'll leave you. For a long time Israel didn't have the real God \u2014 no priest to help, no teacher, no book. But when they were in trouble and got serious, and decided to seek God, the God of Israel \u2014 God let himself be found. Back then it was a dog-eat-dog world; life was constantly up for grabs \u2014 no one, no matter the country, knew what the next day might bring. Nation battered nation, city pummeled city. God let loose every kind of trouble among them.\u201d",
   "ko":"그때 하나님의 영에 감동된 오벳의 아들 아사랴가 아사를 맞으러 나갔어. 그가 말했지. \u201c잘 들어, 아사야 \u2014 유다와 베냐민아, 들어라. 너희가 하나님과 함께하면 하나님도 너희와 함께하실 거야. 그를 찾으면 만나주실 거고, 버리면 너희도 버리실 거야. 오랫동안 이스라엘에게는 참 하나님이 없었어. 도울 제사장도, 가르칠 스승도, 책도 없었지. 하지만 환난 중에 진심으로 돌이켜 이스라엘의 하나님을 찾기로 하면 \u2014 하나님이 만나주셨어. 그때는 약육강식의 세상이었어. 삶이 늘 위태로웠지. 어느 나라든 내일이 어떻게 될지 아는 사람이 없었어. 나라가 나라를 치고, 성읍이 성읍을 쳤지. 하나님이 온갖 환난을 그들 가운데 푸셨어.\u201d"},
  {"badge":"7","mr":"7",
   "en":"\u201cBut it's different with you: be strong. Take heart. Payday is coming!\u201d",
   "ko":"\u201c하지만 너희는 달라. 강해져. 용기를 내. 보상의 날이 오고 있어!\u201d"},
  {"badge":"8-9","mr":"8-9",
   "en":"When Asa heard the prophecy of Azariah son of Obed, he took a deep breath, rolled up his sleeves, and went to work. He cleaned out the disgusting, polluting shrines from the whole country of Judah and Benjamin, and from the towns he had captured in the hill country of Ephraim. He repaired the Altar of God that stood in front of The Temple porch. Then he called a huge assembly \u2014 all of Judah and Benjamin, plus people from Ephraim, Manasseh, and Simeon who were living there at the time. (Many from Israel had left their homes and joined Asa when they saw that God was on his side.)",
   "ko":"오벳의 아들 아사랴의 예언을 들은 아사는 심호흡을 하고 소매를 걷어붙인 뒤 일에 착수했어. 유다와 베냐민 온 땅, 그리고 에브라임 산지에서 점령한 성읍들에서 역겹고 더럽히는 산당들을 쓸어냈지. 성전 현관 앞에 있는 하나님의 제단을 단장했어. 그리고 대집회를 열었어. 유다와 베냐민 전체에, 당시 그곳에 살던 에브라임\u00b7므낫세\u00b7시므온 사람들까지. (하나님이 아사 편이심을 보고 이스라엘에서 많은 사람이 고향을 떠나 아사에게 합류했거든.)"},
  {"badge":"10-15","mr":"10-15",
   "en":"They all came to Jerusalem in the third month of the fifteenth year of Asa's reign for a great worship assembly. From their earlier plunder they sacrificed seven hundred oxen and seven thousand sheep in worship. Then they bound themselves in a covenant to seek God, the God of their ancestors, with all their hearts, holding nothing back. And they agreed that anyone who refused to seek God, the God of Israel, would be put to death \u2014 no matter who: young or old, man or woman. They shouted out their promise to God \u2014 a joyful sound with trumpets and rams' horns blasting. The whole country felt good about the covenant promise; they had made it joyfully, from the heart. They had sought God expecting the best \u2014 and he showed up, ready to be found. God gave them peace inside and out \u2014 a most peaceable kingdom!",
   "ko":"그들이 아사 왕 15년 3월에 예루살렘에 모여 대예배 집회를 열었어. 전에 얻은 전리품에서 소 700마리와 양 7,000마리를 잡아 예배로 드렸지. 그리고 조상들의 하나님을 마음을 다해, 아무것도 남김없이 찾기로 언약을 맺었어. 이스라엘의 하나님을 찾기를 거부하는 자는 누구든 \u2014 어리든 늙었든, 남자든 여자든 \u2014 죽이기로 합의했지. 하나님께 약속을 외쳤는데, 나팔과 숫양 뿔나팔이 울리는 기쁜 소리였어. 온 나라가 그 언약 약속을 기쁘게 여겼어. 마음에서 우러나 기쁘게 약속했거든. 최선을 기대하며 하나님을 찾았더니 \u2014 하나님이 나타나 만나주셨어. 하나님이 안팎으로 평화를 주셨지 \u2014 그야말로 태평성대였어!"},
  {"badge":"16-19","mr":"16-19",
   "en":"In his cleanup, Asa went so far as to remove his own mother, Queen Maacah, from her royal position \u2014 because she had built a shockingly obscene image of Asherah, the sex goddess. Asa tore it down, smashed it to pieces, and burned it in the Kidron Valley. Unfortunately, he didn't manage to get rid of the local neighborhood shrines. But his heart was in the right place \u2014 he stayed loyal to God. All the gold and silver vessels and artifacts that he and his father had set apart for holy use, he installed in The Temple of God. And there wasn't a trace of war until the thirty-fifth year of Asa's reign.",
   "ko":"정화 작업 중에 아사는 자기 어머니 마아가 왕후까지 왕후 자리에서 끌어내렸어 \u2014 아세라라는 음란 여신의 역겨운 우상을 만들었기 때문이야. 아사가 그것을 헐어 산산조각 내고 기드론 골짜기에서 불태웠지. 아쉽게도 동네 산당들까지는 없애지 못했어. 하지만 마음은 바른 곳에 있었어 \u2014 하나님께 충성했거든. 자기와 아버지가 거룩한 용도로 구별해둔 금은 기물들을 모두 하나님의 성전에 들여놓았어. 아사 왕 35년까지 전쟁의 기미조차 없었어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 15장 5문단 1:1 매핑)"],
},
16: {
 "title_en": "Asa's Costly Mistake",
 "title_ko": "아사의 값비싼 실수",
 "units": [
  {"badge":"1","mr":"1",
   "en":"But in the thirty-sixth year of Asa's reign, Baasha king of Israel attacked. He started building a fort at Ramah, closing the border between Israel and Judah to keep Asa, king of Judah, from going in or out.",
   "ko":"그런데 아사 왕 36년에 이스라엘 왕 바아사가 쳐들어왔어. 라마에 요새를 쌓기 시작하면서 이스라엘과 유다 사이 국경을 막아, 유다 왕 아사가 드나들지 못하게 했지."},
  {"badge":"2-3","mr":"2-3",
   "en":"Asa took silver and gold from the treasuries of The Temple of God and the royal palace, and sent it to Ben-Hadad, king of Aram, who lived in Damascus, with this message: \u201cLet's make a treaty, like the one between our fathers. I'm showing my good faith with this gift of silver and gold. Break your deal with Baasha, king of Israel, so he'll stop fighting me.\u201d",
   "ko":"아사가 하나님의 성전과 왕궁 곳간에서 은금을 꺼내 다마스쿠스에 사는 아람 왕 벤하닷에게 보내며 이렇게 전했어. \u201c우리 아버지들 사이의 조약처럼 우리도 조약을 맺읍시다. 은금 예물로 성의를 보입니다. 이스라엘 왕 바아사와의 계약을 깨뜨려서 그가 나를 치지 못하게 하소서.\u201d"},
  {"badge":"4-5","mr":"4-5",
   "en":"Ben-Hadad went along with King Asa and sent his troops against the towns of Israel. They sacked Ijon, Dan, Abel Maim, and all the store-cities of Naphtali. When Baasha got the report, he quit fortifying Ramah.",
   "ko":"벤하닷이 아사 왕의 제안을 받아들여 군대를 이스라엘 성읍들로 보냈어. 이욘, 단, 아벨마임을 함락시키고 납달리의 모든 저장성들을 약탈했지. 바아사가 보고를 받고 라마 요새 공사를 중단했어."},
  {"badge":"6","mr":"6",
   "en":"Then King Asa ordered all the people of Judah to haul away the logs and stones Baasha had used to fortify Ramah, and used them to fortify Geba and Mizpah instead.",
   "ko":"그러자 아사 왕이 유다 백성 전체에게 명령해서 바아사가 라마 요새에 쓴 목재와 돌을 다 뜯어다가 게바와 미스바를 요새화하는 데 썼어."},
  {"badge":"7-9","mr":"7-9",
   "en":"Right after that, Hanani the seer came to Asa, king of Judah, and said, \u201cBecause you went for help to the king of Aram instead of asking God for help, you've lost a victory over the army of the king of Aram. Didn't the Ethiopians and Libyans come at you with far superior forces \u2014 completely outclassing you with their chariots and cavalry? But you asked God for help, and he gave you the victory. God is always on the alert, constantly looking for people who are totally committed to him. You were foolish to go for human help when you could have had God's help. Now you're in trouble \u2014 it's going to be one war after another.\u201d",
   "ko":"바로 그때 선견자 하나니가 유다 왕 아사에게 와서 말했어. \u201c왕이 하나님께 도움을 구하지 않고 아람 왕에게 도움을 청했기 때문에 아람 왕 군대에 대한 승리를 놓쳤소. 구스 사람과 룹 사람들이 월등한 병력으로 \u2014 전차와 기병으로 왕을 완전히 압도하며 \u2014 쳐들어오지 않았소? 그런데 왕이 하나님께 도움을 청했더니 승리를 주셨잖소. 하나님은 늘 깨어 계시며, 온전히 헌신하는 사람을 끊임없이 찾으시오. 하나님의 도움을 받을 수 있었는데 사람의 도움을 청하다니 어리석었소. 이제 곤란해졌소 \u2014 앞으로 전쟁이 꼬리를 물 거요.\u201d"},
  {"badge":"10","mr":"10",
   "en":"At that, Asa lost his temper. Furious, he threw Hanani into the prison stocks. And at the same time, Asa started abusing some of his own people.",
   "ko":"그 말을 듣고 아사가 화를 냈어. 격분해서 하나니를 차꼬에 가뒀지. 그리고 그 무렵 아사가 자기 백성 중 일부를 학대하기 시작했어."},
  {"badge":"11-14","mr":"11-14",
   "en":"The full account of Asa's life is written in The Chronicles of the Kings of Judah. In the thirty-ninth year of his reign, Asa came down with a severe foot disease. He didn't ask God for help \u2014 he went to the doctors instead. Then Asa died, in the forty-first year of his reign. They buried him in the mausoleum he had built for himself in the City of David. They laid him in a crypt filled with aromatic oils and spices. Then they lit a huge bonfire in his memory.",
   "ko":"아사의 전 생애는 유다 왕들의 연대기에 기록되어 있어. 왕이 된 지 39년째에 아사가 심한 발병에 걸렸어. 하나님께 도움을 구하지 않고 의원들에게 갔지. 그리고 아사가 죽었어. 왕위 41년째였어. 다윗 성에 자기를 위해 지어둔 묘실에 묻었지. 향기로운 기름과 향료로 가득한 석실에 눕혔어. 그리고 그를 추모하는 큰 봉화를 피웠어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 16장 7문단 1:1 매핑)"],
},
}
