# -*- coding: utf-8 -*-
"""2Chronicles ch17-20 teen EN/KO (작업자 D2, MSG 직역 기반 초벌)."""
CHAPTERS = {
17: {
 "title_en": "Jehoshaphat Teaches the Nation",
 "title_ko": "여호사밧, 나라를 가르치다",
 "units": [
  {"badge":"1-6","mr":"1-6","header_en":"Jehoshaphat of Judah","header_ko":"유다의 여호사밧",
   "en":"Asa's son Jehoshaphat became the next king, and he started out by building up his defenses against Israel. He stationed troops in all the fortress cities of Judah and posted garrisons throughout Judah and in the Ephraim towns his father Asa had captured. God was on Jehoshaphat's side, because he stuck to the ways of his father Asa's early years. He didn't fool around with the popular Baal religion \u2014 he sought and followed the God of his father and obeyed him. He wasn't like Israel. God secured the kingdom under his rule and gave him a firm grip on it. Everyone in Judah showed their appreciation by bringing gifts. Jehoshaphat ended up very rich and highly honored. He was single-minded in following God \u2014 and he got rid of the local Asherah shrines.",
   "ko":"아사의 아들 여호사밧이 다음 왕이 됐어. 먼저 이스라엘에 대비해 방비를 다지는 일부터 시작했지. 유다의 모든 요새 성읍에 군대를 주둔시키고, 유다 전역과 아버지 아사가 점령한 에브라임 성읍들에 수비대를 배치했어. 하나님이 여호사밧 편이셨는데, 아버지 아사의 초기 시절 방식을 고수했기 때문이야. 유행하던 바알 종교에 손대지 않았어. 아버지의 하나님을 찾고 따르며 순종했지. 이스라엘과는 달랐어. 하나님이 그의 다스림 아래 나라를 굳게 세우시고 확고히 잡게 하셨어. 유다 온 백성이 예물을 가져와 감사를 표했지. 여호사밧은 크게 부유해지고 크게 존귀해졌어. 하나님 따르는 일에 한마음이었어. 동네 아세라 산당들도 없애버렸지."},
  {"badge":"7-9","mr":"7-9",
   "en":"In the third year of his reign, he sent his officials on a teaching mission to the cities of Judah \u2014 excellent men, every one of them: Ben-Hail, Obadiah, Zechariah, Nethanel, and Micaiah. They were joined by Levites \u2014 Shemaiah, Nethaniah, Zebadiah, Asahel, Shemiramoth, Jehonathan, Adonijah, Tobijah, and Tob-Adonijah \u2014 plus the priests Elishama and Jehoram. They made a circuit of the towns of Judah, teaching the people with the Book of The Revelation of God as their textbook.",
   "ko":"왕이 된 지 3년째에 신하들을 유다 성읍들로 교육 선교를 보냈어. 하나같이 훌륭한 사람들이었지. 벤하일, 오바댜, 스가랴, 느다넬, 미가야. 레위인들도 동행했어. 스마야, 느다냐, 스바댜, 아사헬, 스미라못, 여호나단, 아도니야, 도비야, 돕아도니야. 제사장 엘리사마와 여호람도 함께였지. 그들이 유다의 성읍들을 순회하며 하나님의 계시의 책을 교과서 삼아 백성을 가르쳤어."},
  {"badge":"10-12","mr":"10-12",
   "en":"A deep fear of God settled over all the kingdoms around Judah \u2014 none of them dared go to war against Jehoshaphat. Some Philistines even brought him gifts and loads of silver, and the desert bedouin brought flocks: 7,700 rams and 7,700 goats. Jehoshaphat grew stronger every day, building more and more forts and store-cities. It was an age of prosperity for Judah!",
   "ko":"유다 주변 모든 나라에 하나님에 대한 깊은 두려움이 임했어. 감히 여호사밧과 전쟁하려는 나라가 없었지. 블레셋 사람들 중에는 예물과 많은 은을 가져온 이들도 있었고, 사막 유목민들은 가축 떼를 가져왔어. 숫양 7,700마리와 염소 7,700마리. 여호사밧은 날로 강성해져 요새와 저장성을 계속 늘려 지었어. 유다의 번영 시대였지!"},
  {"badge":"13-19","mr":"13-19",
   "en":"He also kept excellent fighting men stationed in Jerusalem. The captains of Judah's military units, listed by families, were: Captain Adnah with 300,000 soldiers; his associate Captain Jehohanan with 280,000; his associate Amasiah son of Zicri \u2014 a volunteer for God \u2014 with 200,000. Eliada represented Benjamin with 200,000 men fully equipped with bow and shield, and his associate Jehozabad had 180,000 armed and ready for battle. These were under the king's direct command \u2014 and that was on top of the troops posted in the fortress cities all over Judah.",
   "ko":"예루살렘에도 정예 전투병을 주둔시켰어. 유다 군부대 지휘관들을 가문별로 정리하면 이래. 아드나 지휘관 휘하 30만 명, 부관 여호하난 휘하 28만 명, 부관 시그리의 아들 아마샤 \u2014 하나님께 자원한 자 \u2014 휘하 20만 명. 엘리아다는 베냐민 대표로 활과 방패로 완전무장한 20만 명, 부관 여호사밧은 전투 준비 완료된 18만 명. 이들은 왕의 직속 지휘를 받았어. 유다 전역 요새 성읍에 배치된 군대는 별도였지."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 17장 4문단 1:1 매핑)"],
},
18: {
 "title_en": "Micaiah's Warning Nobody Wanted",
 "title_ko": "아무도 듣기 싫어한 미가야의 경고",
 "units": [
  {"badge":"1-3","mr":"1-3",
   "en":"But even though Jehoshaphat was very rich and highly honored, he made a marriage alliance with Ahab, king of Israel. Some time later he paid Ahab a visit at Samaria. Ahab threw a huge feast for the visit \u2014 a massive barbecue with all the lamb and beef you could eat. But Ahab had a hidden agenda: he wanted Jehoshaphat's support in attacking Ramoth Gilead. Then Ahab brought it into the open: \u201cWill you join me in attacking Ramoth Gilead?\u201d Jehoshaphat said, \u201cYou bet. I'm with you all the way \u2014 you can count on me and my troops.\u201d",
   "ko":"그런데 여호사밧이 크게 부유하고 존귀했음에도 이스라엘 왕 아합과 혼인 동맹을 맺었어. 얼마 후 사마리아에 있는 아합을 방문했지. 아합이 방문을 축하하며 큰 잔치를 열었어. 양고기와 소고기가 끝없이 나오는 어마어마한 바비큐였지. 하지만 아합에게는 숨은 속셈이 있었어. 길르앗 라못을 치는 데 여호사밧의 지원을 원했던 거야. 그러더니 아합이 본심을 드러냈지. \u201c길르앗 라못을 치는 데 함께하시겠소?\u201d 여호사밧이 말했어. \u201c물론이죠. 끝까지 함께할게요. 저와 제 군대를 믿으셔도 돼요.\u201d"},
  {"badge":"4","mr":"4",
   "en":"Then Jehoshaphat said, \u201cBut before you do anything, ask God for guidance.\u201d",
   "ko":"그러자 여호사밧이 말했어. \u201c하지만 뭐든 하기 전에 하나님께 먼저 여쭤봅시다.\u201d"},
  {"badge":"5","mr":"5",
   "en":"The king of Israel gathered the prophets together \u2014 all four hundred of them \u2014 and put the question to them: \u201cShould I attack Ramoth Gilead, or should I hold back?\u201d \u201cGo for it,\u201d they said. \u201cGod will hand it over to the king.\u201d",
   "ko":"이스라엘 왕이 선지자들을 모았어. 전부 400명이었지. 그리고 물었어. \u201c길르앗 라못을 칠까요, 말까요?\u201d \u201c가세요,\u201d 그들이 말했어. \u201c하나님이 왕의 손에 넘겨주실 겁니다.\u201d"},
  {"badge":"6","mr":"6",
   "en":"But Jehoshaphat dragged his feet. \u201cIs there another prophet of God around here we can ask? Let's get a second opinion.\u201d",
   "ko":"하지만 여호사밧이 머뭇거렸어. \u201c여기 여쭤볼 만한 다른 하나님의 선지자는 없나요? 두 번째 의견을 들어봅시다.\u201d"},
  {"badge":"7","mr":"7",
   "en":"The king of Israel told Jehoshaphat, \u201cAs a matter of fact, there is one more. But I hate him. He never has anything good to say about me \u2014 only doom, doom, doom. Micaiah son of Imlah.\u201d \u201cThe king shouldn't talk about a prophet of God like that!\u201d said Jehoshaphat.",
   "ko":"이스라엘 왕이 여호사밧에게 말했어. \u201c사실 한 명이 더 있긴 합니다. 하지만 난 그가 싫어요. 나에 대해 좋은 말은 절대 안 하고 재앙, 재앙, 재앙만 말하거든요. 이믈라의 아들 미가야요.\u201d \u201c왕은 하나님의 선지자를 그렇게 말하면 안 됩니다!\u201d 여호사밧이 말했어."},
  {"badge":"8","mr":"8",
   "en":"So the king of Israel ordered one of his servants, \u201cQuickly \u2014 get Micaiah son of Imlah.\u201d",
   "ko":"그래서 이스라엘 왕이 신하 하나에게 명령했어. \u201c빨리, 이믈라의 아들 미가야를 데려와.\u201d"},
  {"badge":"9-11","mr":"9-11",
   "en":"Meanwhile, the king of Israel and Jehoshaphat were sitting on their thrones in their royal robes, looking magnificent in front of the Samaria city gates. All the prophets were putting on a prophecy show for them. Zedekiah son of Kenaanah had even made a set of iron horns, and waving them around, he shouted, \u201cThis is God's word! With these horns you'll gore Aram until there's nothing left of them!\u201d All the prophets chimed in: \u201cYes! Go for Ramoth Gilead! An easy victory! God's gift to the king!\u201d",
   "ko":"그사이 이스라엘 왕과 여호사밧은 왕복을 입고 사마리아 성문 앞 위엄 있는 모습으로 왕좌에 앉아 있었어. 모든 선지자들이 그들을 위해 예언 퍼포먼스를 펼치고 있었지. 그나아나의 아들 시드기야는 쇠뿔 한 쌍까지 만들어서 흔들며 외쳤어. \u201c하나님의 말씀이다! 이 뿔들로 아람을 들이받아 남김없이 없애버릴 것이다!\u201d 모든 선지자가 맞장구를 쳤어. \u201c그래요! 길르앗 라못으로 가세요! 쉬운 승리입니다! 왕께 주시는 하나님의 선물이에요!\u201d"},
  {"badge":"12","mr":"12",
   "en":"The messenger who went to get Micaiah told him, \u201cThe prophets have all said Yes to the king. Make it unanimous \u2014 vote Yes!\u201d",
   "ko":"미가야를 데리러 간 전령이 그에게 말했어. \u201c선지자들이 모두 왕께 찬성이라고 했습니다. 만장일치로 만드세요. 찬성표를 던지세요!\u201d"},
  {"badge":"13","mr":"13",
   "en":"But Micaiah said, \u201cAs sure as God lives, whatever God says \u2014 that's what I'll say.\u201d",
   "ko":"하지만 미가야가 말했어. \u201c하나님이 살아 계심같이, 하나님이 하시는 말씀 그대로 말하겠소.\u201d"},
  {"badge":"14","mr":"14",
   "en":"With Micaiah standing before him, the king asked, \u201cSo, Micaiah \u2014 do we attack Ramoth Gilead, or do we hold back?\u201d \u201cGo ahead,\u201d he said, \u201can easy victory! God's gift to the king.\u201d",
   "ko":"미가야가 앞에 서자 왕이 물었어. \u201c자, 미가야. 길르앗 라못을 치는 거야, 마는 거야?\u201d \u201c가십시오,\u201d 그가 말했어. \u201c쉬운 승리입니다! 왕께 주시는 하나님의 선물이에요.\u201d"},
  {"badge":"15","mr":"15",
   "en":"\u201cNot so fast,\u201d said the king. \u201cHow many times have I made you swear to tell me the truth and nothing but the truth?\u201d",
   "ko":"\u201c너무 성급하군,\u201d 왕이 말했어. \u201c진실만을, 진실 이외에는 아무것도 말하지 않겠다고 내가 몇 번이나 맹세시켰나?\u201d"},
  {"badge":"16","mr":"16",
   "en":"\u201cAll right,\u201d said Micaiah, \u201csince you insist... I saw all of Israel scattered over the hills like sheep with no shepherd. Then God spoke: 'These poor people have no one to tell them what to do. Let them go home and do the best they can for themselves.'\u201d",
   "ko":"\u201c알겠습니다,\u201d 미가야가 말했어. \u201c고집하시니... 온 이스라엘이 목자 없는 양처럼 산에 흩어진 것을 보았습니다. 그때 하나님이 말씀하셨어. '이 불쌍한 백성에게는 지시할 사람이 없구나. 집으로 돌려보내 각자 알아서 하게 하라.'\u201d"},
  {"badge":"17","mr":"17",
   "en":"The king of Israel turned to Jehoshaphat. \u201cSee! What did I tell you? He never has a good word for me from God \u2014 only doom.\u201d",
   "ko":"이스라엘 왕이 여호사밧을 돌아보며 말했어. \u201c보세요! 내가 뭐라고 했어요? 하나님에게서 나에 대한 좋은 말은 절대 안 해요. 재앙뿐이죠.\u201d"},
  {"badge":"18-21","mr":"18-21",
   "en":"Micaiah kept going. \u201cI'm not done yet \u2014 listen to God's word: I saw God sitting on his throne, with all the Angel Armies of heaven standing at attention on his right and his left. And God said, 'How can we get Ahab to attack Ramoth Gilead?' Some suggested this, some suggested that. Then a bold angel stepped forward, stood before God, and said, 'I'll do it.' 'And how will you do it?' said God. 'Easy,' said the angel. 'I'll get all the prophets to lie.' 'That should do it,' said God. 'On your way \u2014 go seduce him!'\u201d",
   "ko":"미가야가 계속 말했어. \u201c아직 안 끝났습니다. 하나님의 말씀을 들으십시오. 하나님이 보좌에 앉으신 것을 보았는데, 하늘의 천사 군대가 좌우에 도열해 시립해 있었어요. 하나님이 말씀하셨어. '어떻게 하면 아합이 길르앗 라못을 치게 할 수 있을까?' 이 천사는 이걸, 저 천사는 저걸 제안했어요. 그때 담대한 천사 하나가 앞으로 나와 하나님 앞에 서서 말했어요. '제가 하겠습니다.' '어떻게 할 건데?' 하나님이 물으셨어. '쉽습니다,' 천사가 말했어요. '모든 선지자가 거짓말하게 하겠습니다.' '그거면 되겠군,' 하나님이 말씀하셨어. '가라, 그를 꾀어라!'\u201d"},
  {"badge":"22","mr":"22",
   "en":"\u201cAnd that's exactly what has happened. God has filled the mouths of your puppet prophets with seductive lies. God has pronounced your doom.\u201d",
   "ko":"\u201c그리고 바로 그 일이 일어났습니다. 하나님이 왕의 꼭두각시 선지자들의 입에 꾀는 거짓말을 가득 채우셨어요. 하나님이 왕의 재앙을 선언하신 겁니다.\u201d"},
  {"badge":"23","mr":"23",
   "en":"Just then Zedekiah son of Kenaanah walked up and slapped Micaiah across the face. \u201cSince when did the Spirit of God leave me and go to you?\u201d he demanded.",
   "ko":"바로 그때 그나아나의 아들 시드기야가 다가와 미가야의 뺨을 때렸어. \u201c하나님의 영이 언제 나를 떠나 너에게로 갔다는 거냐?\u201d 따졌지."},
  {"badge":"24","mr":"24",
   "en":"Micaiah said, \u201cYou'll find out soon enough \u2014 you'll know it when you're desperately hunting for a place to hide.\u201d",
   "ko":"미가야가 말했어. \u201c곧 알게 될 거요. 숨을 곳을 필사적으로 찾아 헤맬 때 알게 될 거요.\u201d"},
  {"badge":"25-26","mr":"25-26",
   "en":"The king of Israel had heard enough. \u201cGet Micaiah out of here! Hand him over to Amon the city governor and to Joash the king's son, with this message: 'King's orders! Lock him up in prison. Keep him on bread and water until I get back safe and sound.'\u201d",
   "ko":"이스라엘 왕은 더 들을 수 없었어. \u201c미가야를 여기서 끌어내! 아몬 성읍 장관과 왕자 요아스에게 넘겨라. 이렇게 전하라. '왕명이다! 그를 옥에 가둬라. 내가 무사히 돌아올 때까지 떡과 물만 주며 가둬둬라.'\u201d"},
  {"badge":"27","mr":"27",
   "en":"Micaiah said, \u201cIf you ever make it back safe and sound, then I'm no prophet of God.\u201d Then he added, \u201cEveryone listening \u2014 when this happens, remember where you heard it first!\u201d",
   "ko":"미가야가 말했어. \u201c왕이 무사히 돌아오기만 하면 저는 하나님의 선지자가 아닙니다.\u201d 그리고 덧붙였지. \u201c듣고 있는 모든 사람이여 \u2014 이 일이 일어나거든 어디서 처음 들었는지 기억하시오!\u201d"},
  {"badge":"28-29","mr":"28-29",
   "en":"So the king of Israel and Jehoshaphat, king of Judah, went ahead and attacked Ramoth Gilead. The king of Israel said to Jehoshaphat, \u201cYou wear my royal robe \u2014 I'm going into battle in disguise.\u201d So Jehoshaphat wore the robe, and the king of Israel went into battle disguised.",
   "ko":"그래서 이스라엘 왕과 유다 왕 여호사밧이 길르앗 라못을 쳐들어갔어. 이스라엘 왕이 여호사밧에게 말했어. \u201c내 왕복을 당신이 입으시오. 나는 변장하고 전투에 나갈 거요.\u201d 그래서 여호사밧이 왕복을 입었고, 이스라엘 왕은 변장하고 전투에 나갔지."},
  {"badge":"30","mr":"30",
   "en":"Meanwhile, the king of Aram had given orders to his chariot commanders \u2014 all thirty-two of them: \u201cDon't bother with anyone, big or small. Go after the king of Israel, and him only.\u201d",
   "ko":"한편 아람 왕은 전차 지휘관들 \u2014 32명 전원에게 명령을 내려뒀어. \u201c대소 구분 말고 아무도 신경 쓰지 마라. 이스라엘 왕만 노려라. 오직 그만.\u201d"},
  {"badge":"31-32","mr":"31-32",
   "en":"When the chariot commanders saw Jehoshaphat, they shouted, \u201cThere he is! The king of Israel!\u201d and went after him. Jehoshaphat cried out \u2014 and the commanders realized they had the wrong man. It wasn't the king of Israel after all. God stepped in, and they left him alone.",
   "ko":"전차 지휘관들이 여호사밧을 보고 외쳤어. \u201c저기다! 이스라엘 왕이다!\u201d 그리고 쫓아갔지. 여호사밧이 소리를 질렀어. 지휘관들은 잘못 짚었다는 걸 깨달았지. 이스라엘 왕이 아니었던 거야. 하나님이 개입하셔서 그들은 그를 놓아줬어."},
  {"badge":"33","mr":"33",
   "en":"Just then, someone shot an arrow at random into the crowd \u2014 and it struck the king of Israel in a gap in his armor. The king told his chariot driver, \u201cTurn around! Get me out of here \u2014 I'm wounded.\u201d",
   "ko":"바로 그때 누군가 무심코 쏜 화살이 군중 속으로 날아가 이스라엘 왕의 갑옷 틈새를 맞혔어. 왕이 전차병에게 말했어. \u201c돌아가! 여기서 빼내 \u2014 다쳤어.\u201d"},
  {"badge":"34","mr":"34",
   "en":"The battle raged on, hot and heavy, all day long. Propped up in his chariot, the king watched from the sidelines. He died that evening.",
   "ko":"전투는 하루 종일 치열하게 계속됐어. 전차에 몸을 기대고 왕은 곁에서 지켜봤지. 그날 저녁에 죽었어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 18장 24문단 1:1 매핑)"],
},
19: {
 "title_en": "Jehoshaphat's Justice Reform",
 "title_ko": "여호사밧의 사법 개혁",
 "units": [
  {"badge":"1-3","mr":"1-3",
   "en":"But Jehoshaphat, king of Judah, made it home safe and sound. Then Jehu, son of Hanani the seer, confronted King Jehoshaphat: \u201cYou had no business helping evil and cozying up to people who hate God. Because you did this, God is good and angry with you. But you're not all bad \u2014 you swept clean the polluting shrines, and you were single-minded in seeking God.\u201d",
   "ko":"하지만 유다 왕 여호사밧은 무사히 집으로 돌아왔어. 그러자 선견자 하나니의 아들 예후가 여호사밧 왕을 대면했지. \u201c악을 돕고 하나님을 미워하는 자들과 친하게 지낼 일이 뭐요? 이렇게 했으니 하나님이 진노하시오. 하지만 아주 나쁜 건 아니오. 더럽히는 산당들을 깨끗이 쓸어냈고, 하나님 찾기에 한마음이었으니.\u201d"},
  {"badge":"4","mr":"4",
   "en":"Jehoshaphat kept his home in Jerusalem, but he made regular rounds among the people \u2014 from Beersheba in the south all the way to Mount Ephraim in the north \u2014 urging them to return to God, the God of their ancestors.",
   "ko":"여호사밧은 예루살렘에 거처를 두었지만, 백성 사이를 정기적으로 순회했어. 남쪽 브엘세바부터 북쪽 에브라임 산까지 \u2014 조상들의 하나님께 돌아오라고 권면하면서."},
  {"badge":"5-7","mr":"5-7",
   "en":"He was also diligent about appointing judges throughout the land \u2014 every fortress city got its judge. He charged the judges: \u201cThis is serious work \u2014 do it carefully. You're not just settling disputes between people; these are God's judgments you're handing down. Live in the fear of God \u2014 be extremely careful, because God hates dishonesty, favoritism, and bribery.\u201d",
   "ko":"온 땅에 재판관을 세우는 일에도 힘썼어. 모든 요새 성읍에 재판관을 뒀지. 재판관들에게 당부했어. \u201c이건 심각한 일이야. 신중하게 해. 사람들 사이의 분쟁을 해결하는 게 아니야. 너희가 내리는 건 하나님의 판결이야. 하나님을 경외하며 살아 \u2014 극도로 조심해. 하나님은 부정직과 편파와 뇌물을 미워하시니까.\u201d"},
  {"badge":"8-10","mr":"8-10",
   "en":"In Jerusalem, Jehoshaphat also appointed Levites, priests, and family heads to handle matters of worship and to settle local disputes. He charged them: \u201cDo your work in the fear of God \u2014 be dependable and honest in everything you do. When a case comes before you involving any of your fellow citizens \u2014 whether it looks big, like murder, or small, like a question about interpreting the law \u2014 you must warn them that they're dealing with God. Make that crystal clear. Otherwise, both you and they will face God's anger. Do your work well, or you'll end up just as guilty as they are.\u201d",
   "ko":"예루살렘에서는 레위인과 제사장과 족장들을 세워 예배 관련 일과 지역 분쟁을 다루게 했어. 당부했지. \u201c하나님을 경외하며 일해. 모든 일에 믿음직하고 정직해. 동포가 관련된 사건이 너희 앞에 오거든 \u2014 살인 같은 큰 일이든, 율법 해석 같은 작은 문제든 \u2014 그들이 하나님을 상대하고 있음을 경고해야 해. 분명히 밝혀. 그렇지 않으면 너희도 그들도 하나님의 진노를 맞을 거야. 일을 잘해. 아니면 너희도 그들만큼 유죄가 될 거야.\u201d"},
  {"badge":"11","mr":"11",
   "en":"\u201cAmariah the chief priest is in charge of all cases involving the worship of God; Zebadiah son of Ishmael, the leader of the tribe of Judah, is in charge of all civil cases; and the Levites will keep order in the courts. Be bold and diligent \u2014 and may God be with you as you do your best.\u201d",
   "ko":"\u201c대제사장 아마랴가 하나님 예배 관련 모든 사건을 맡고, 유다 지파의 지도자 이스마엘의 아들 스바댜가 모든 민사 사건을 맡을 거야. 레위인들은 법정 질서를 유지해. 담대하고 부지런해. 최선을 다하는 너희와 하나님이 함께하시길.\u201d"},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 19장 5문단 1:1 매핑)"],
},
20: {
 "title_en": "The Battle You Don't Have to Fight",
 "title_ko": "싸우지 않아도 되는 전쟁",
 "units": [
  {"badge":"1-2","mr":"1-2",
   "en":"Some time later, the Moabites and Ammonites \u2014 along with the Meunites \u2014 joined forces to make war on Jehoshaphat. Jehoshaphat got this intelligence report: \u201cA huge army is on its way from beyond the Dead Sea to fight you. There's no time to waste \u2014 they're already at Hazazon Tamar, the oasis of En Gedi.\u201d",
   "ko":"얼마 후 모압 사람과 암몬 사람이 마온 사람과 함께 연합해서 여호사밧을 치러 왔어. 여호사밧이 이런 첩보를 받았지. \u201c사해 너머에서 대군이 왕을 치러 오고 있습니다. 지체할 시간이 없어요. 이미 하사손다말, 곧 엔게디 오아시스에 도착했습니다.\u201d"},
  {"badge":"3-4","mr":"3-4",
   "en":"Shaken, Jehoshaphat prayed. He turned to God for help and ordered a nationwide fast. All of Judah united in seeking God's help \u2014 people came from every city in Judah to pray to God.",
   "ko":"여호사밧은 흔들렸지만 기도했어. 하나님께 도움을 구하며 전국에 금식을 선포했지. 온 유다가 하나님의 도움을 구하는 데 하나가 됐어. 유다 모든 성읍에서 사람들이 하나님께 기도하러 왔지."},
  {"badge":"5-9","mr":"5-9",
   "en":"Then Jehoshaphat stood before the assembled people of Judah and Jerusalem at The Temple of God, in front of the new courtyard, and prayed: \u201cO God, God of our ancestors \u2014 are you not God in heaven above and ruler of all the kingdoms below? You hold all power and might in your fist \u2014 no one stands a chance against you! And didn't you drive out the natives of this land as you brought your people Israel in, giving it permanently to the descendants of Abraham, your friend? They've lived here and built a holy house of worship to honor you, saying, 'When the worst happens \u2014 whether war or flood or disease or famine \u2014 and we stand before this Temple (we know you are personally present in this place!) and cry out our pain and trouble, we know you will listen and give us victory.'\u201d",
   "ko":"그러자 여호사밧이 유다와 예루살렘의 모인 백성 앞에, 하나님의 성전 새 뜰 앞에서 서서 기도했어. \u201c하나님, 우리 조상들의 하나님 \u2014 위로 하늘의 하나님이시며 아래 모든 나라의 다스리시는 분이 아니십니까? 모든 권능을 주먹에 쥐고 계시니 아무도 당신을 당할 수 없습니다! 주의 백성 이스라엘을 들이실 때 이 땅 원주민을 쫓아내시고 주의 친구 아브라함의 자손에게 영원히 주지 않으셨습니까? 그들이 여기 살며 주를 높이는 거룩한 예배의 집을 짓고 말했습니다. '최악의 일이 \u2014 전쟁이든 홍수든 질병이든 기근이든 \u2014 닥치면 이 성전 앞에 서서 (주께서 이 곳에 친히 계심을 압니다!) 고통과 환난을 아뢰면, 주께서 들으시고 승리를 주실 줄 압니다.'\u201d"},
  {"badge":"10-12","mr":"10-12",
   "en":"\u201cAnd now it's happened: men from Ammon, Moab, and Mount Seir have shown up. You didn't let Israel touch them when we first arrived here \u2014 we detoured around them and never laid a hand on them. And now they've come to kick us out of the country you gave us! O dear God, won't you deal with them? We're helpless against this vandal horde that's ready to attack us. We don't know what to do \u2014 we're looking to you.\u201d",
   "ko":"\u201c그리고 이제 그 일이 일어났습니다. 암몬과 모압과 세일 산 사람들이 나타났어요. 처음 이곳에 왔을 때 이스라엘이 그들을 건드리지 못하게 하셨죠. 우회해서 지나갔고 손도 대지 않았어요. 그런데 이제 그들이 주께서 주신 나라에서 우리를 쫓아내려 합니다! 사랑하는 하나님, 그들을 처리해주시지 않겠습니까? 우리를 치려는 이 약탈 무리 앞에서 우리는 무력합니다. 어떻게 해야 할지 모르겠어요. 주만 바라봅니다.\u201d"},
  {"badge":"13","mr":"13",
   "en":"Everyone in Judah was there \u2014 little children, wives, sons \u2014 all present and paying attention to God.",
   "ko":"유다 온 백성이 거기 있었어. 어린아이들, 아내들, 아들들 \u2014 모두 하나님께 주목하며 자리했지."},
  {"badge":"14-17","mr":"14-17",
   "en":"Then Jahaziel was moved by the Spirit of God to speak in the middle of the congregation. (Jahaziel was the son of Zechariah, the son of Benaiah, the son of Jeiel, the son of Mattaniah the Levite, of the Asaph clan.) He said, \u201cAttention, everyone \u2014 all of you from out of town, all of Jerusalem, and you, King Jehoshaphat \u2014 this is God's word: Don't be afraid; don't even think about this vandal horde. This is God's war, not yours. Tomorrow, go out against them \u2014 look, they're already coming up the slopes of Ziz. You'll meet them at the end of the ravine near the wilderness of Jeruel. You won't have to lift a finger in this battle. Just stand firm, Judah and Jerusalem, and watch God rescue you. Don't be afraid, don't waver. March out boldly tomorrow \u2014 God is with you.\u201d",
   "ko":"그때 야하시엘이 하나님의 영에 감동되어 회중 가운데서 말했어. (야하시엘은 스가랴의 아들, 브나야의 손자, 여이엘의 증손, 아삽 가문의 레위인 맛다냐의 현손이야.) 그가 말했지. \u201c주목하시오, 여러분 \u2014 지방에서 온 모든 분, 예루살렘 모든 분, 그리고 여호사밧 왕 \u2014 하나님의 말씀입니다. 두려워 마시오. 이 약탈 무리는 신경도 쓰지 마시오. 이건 하나님의 전쟁이지 여러분의 전쟁이 아니오. 내일 그들을 맞으러 나가시오. 보시오, 벌써 시스 비탈을 오르고 있소. 여루엘 광야 근처 골짜기 끝에서 만날 거요. 이 전투에서는 손가락 하나 까딱 안 해도 되오. 굳게 서시오, 유다와 예루살렘아. 하나님이 구원하시는 것을 지켜보시오. 두려워 말고 흔들리지 마시오. 내일 담대히 행진하시오. 하나님이 함께하시오.\u201d"},
  {"badge":"18-19","mr":"18-19",
   "en":"Then Jehoshaphat knelt down, bowing with his face to the ground. All of Judah and Jerusalem did the same, worshiping God. The Levites \u2014 both Kohathites and Korahites \u2014 jumped to their feet to praise God, the God of Israel. They praised at the top of their lungs!",
   "ko":"그러자 여호사밧이 무릎을 꿇고 얼굴을 땅에 대고 엎드렸어. 유다와 예루살렘 전체도 따라 하며 하나님께 경배했지. 레위인들 \u2014 그핫 자손과 고라 자손 \u2014 이 일어나 이스라엘의 하나님을 찬양했어. 목청껏 찬양했지!"},
  {"badge":"20","mr":"20",
   "en":"They were up early in the morning, ready to march into the wilderness of Tekoa. As they set out, Jehoshaphat stood up and said, \u201cListen, Judah and Jerusalem! Hear me out! Believe firmly in God, your God, and your lives will stand firm! Believe in his prophets, and you'll come out on top!\u201d",
   "ko":"이른 아침에 일어나 드고아 광야로 행진할 준비를 했어. 출발하면서 여호사밧이 일어나 말했지. \u201c들어라, 유다와 예루살렘아! 내 말을 들어라! 너희 하나님을 굳게 믿어라. 그러면 너희 삶도 굳게 설 거야! 그의 선지자들을 믿어라. 그러면 승리할 거야!\u201d"},
  {"badge":"21","mr":"21",
   "en":"After talking it over with the people, Jehoshaphat appointed a choir to sing for God. Dressed in holy robes, they marched ahead of the troops, singing: \u201cGive thanks to God \u2014 his love never quits.\u201d",
   "ko":"백성과 상의한 후 여호사밧이 하나님을 위한 성가대를 세웠어. 거룩한 예복을 입고 군대 앞에서 행진하며 노래했지. \u201c하나님께 감사하라 \u2014 그의 사랑은 영원히 끝나지 않는다.\u201d"},
  {"badge":"22-23","mr":"22-23",
   "en":"The moment they started shouting and praising, God set ambushes against the men of Ammon, Moab, and Mount Seir who were attacking Judah \u2014 and they all ended up dead. The Ammonites and Moabites mistakenly attacked the men from Mount Seir and massacred them. Then, even more confused, they turned on each other \u2014 and every last one of them was killed.",
   "ko":"그들이 외치며 찬양하기 시작하자마자 하나님이 유다를 치던 암몬과 모압과 세일 산 사람들 사이에 매복을 두셨어. 결국 다 죽었지. 암몬 사람과 모압 사람이 착각해서 세일 산 사람들을 공격해 몰살시켰어. 그러다 더 혼란스러워져서 서로 치고받았고 \u2014 전부 죽었어."},
  {"badge":"24","mr":"24",
   "en":"When Judah came up over the hill and looked out over the wilderness at the barbarian horde, all they saw was a field of dead bodies \u2014 not a single living soul.",
   "ko":"유다가 언덕에 올라 광야의 오랑캐 무리를 내려다보니, 보이는 건 시체밭뿐이었어. 살아 있는 목숨이 하나도 없었지."},
  {"badge":"25-26","mr":"25-26",
   "en":"When Jehoshaphat and his people went to carry off the plunder, they found more loot than they could carry \u2014 equipment, clothing, valuables. It took three whole days to cart it all away! On the fourth day they gathered at the Valley of Blessing (Beracah) and blessed God there. (That's how the valley got its name \u2014 Valley of Blessing.)",
   "ko":"여호사밧과 백성이 전리품을 거두러 가보니 가져갈 수 없을 만큼 많은 노획물이 있었어. 장비, 의복, 귀중품. 다 실어 나르는 데 꼬박 3일이 걸렸어! 나흘째 되는 날 축복 골짜기(브라가)에 모여 하나님을 송축했지. (그래서 그 골짜기 이름이 축복 골짜기가 됐어.)"},
  {"badge":"27-28","mr":"27-28",
   "en":"Then Jehoshaphat led all the men of Judah and Jerusalem back to Jerusalem \u2014 a joyful parade. God had given them sweet relief from their enemies! They entered Jerusalem and marched to The Temple of God with the whole band playing.",
   "ko":"그러자 여호사밧이 유다와 예루살렘 모든 사람을 이끌고 예루살렘으로 돌아왔어. 기쁨의 행진이었지. 하나님이 원수들에게서 달콤한 안식을 주셨거든! 예루살렘에 입성해 온 악단이 연주하는 가운데 하나님의 성전으로 행진했어."},
  {"badge":"29-30","mr":"29-30",
   "en":"When the surrounding kingdoms heard that God himself had fought Israel's enemies, the fear of God fell on them. Jehoshaphat never heard another peep from them \u2014 as long as Jehoshaphat reigned, his kingdom was at peace.",
   "ko":"주변 나라들이 하나님 친히 이스라엘의 원수들과 싸우셨다는 소식을 듣자 하나님 두려움이 그들에게 임했어. 여호사밧이 다스리는 동안 다시는 그들에게서 아무 소리도 들리지 않았어. 여호사밧이 왕인 한 나라는 평안했지."},
  {"badge":"31-33","mr":"31-33",
   "en":"That about sums up Jehoshaphat's reign over Judah. He was thirty-five years old when he became king, and he ruled in Jerusalem for twenty-five years. His mother was Azubah, daughter of Shilhi. He lived the way his father Asa had \u2014 no detours, no dead ends \u2014 a life that pleased God. But he never managed to get rid of the neighborhood shrines \u2014 people kept praying and worshiping at those idol shops.",
   "ko":"유다를 다스린 여호사밧의 치세를 요약하면 이 정도야. 왕이 될 때 35살이었고 예루살렘에서 25년 동안 다스렸어. 어머니는 실히의 딸 아수바였지. 아버지 아사처럼 살았어. 곁길도 막다른 길도 없이 \u2014 하나님을 기쁘시게 하는 삶이었지. 하지만 동네 산당은 없애지 못했어. 사람들은 그 우상 가게들에서 계속 기도하고 예배했거든."},
  {"badge":"34","mr":"34",
   "en":"The rest of Jehoshaphat's life, from start to finish, is written in the memoirs of Jehu son of Hanani, which are included in the Royal Annals of Israel's Kings.",
   "ko":"여호사밧의 나머지 생애는 처음부터 끝까지 하나니의 아들 예후의 회고록에 기록되어 있어. 이스라엘 왕들의 왕실 연대기에 포함된 거지."},
  {"badge":"35-37","mr":"35-37",
   "en":"Late in life, Jehoshaphat formed a trading partnership with Ahaziah, king of Israel \u2014 which was very wrong of him. He teamed up with him to build ocean-going ships at Ezion Geber to trade with Tarshish. But Eliezer son of Dodavahu, from Mareshah, spoke out against Jehoshaphat's venture: \u201cBecause you joined forces with Ahaziah, God has wrecked your work.\u201d The ships were smashed to pieces, and the trade partnership came to nothing.",
   "ko":"말년에 여호사밧이 이스라엘 왕 아하시야와 무역 동맹을 맺었어. 매우 잘못한 일이었지. 에시온게벨에서 다시스로 무역할 원양 선박을 건조하려고 손잡은 거야. 하지만 마레사 출신 도다와후의 아들 엘리에셀이 여호사밧의 사업에 반대하며 외쳤어. \u201c아하시야와 손잡았기 때문에 하나님이 왕의 일을 파선시키셨소.\u201d 배들은 산산조각 났고, 무역 동맹은 물거품이 됐어."},
 ],
 "splits": [],
 "changes": ["초벌 작성 (MSG 20장 17문단 1:1 매핑)"],
},
}
